### ISSUE TITLE
Make Request Timeout user parameter and remove log init in libraries.

### ISSUE THREAD

**Issue by mallilinux1978** [dell/PyU4V#10]
Improvement #1.

Make logging centrally configurable by main program? Such away user application will have logging control to tune log levels. Also user does not need make code changes.

Can you replace : 

CONF_FILE = "PyU4V.conf"
LOG = logging.getLogger("PyU4V")
logging.config.fileConfig(CONF_FILE)

with 

LOG = logging.getLogger(__name__)

Improvement #2 .

Introduce method in rest_univmax to override time out. So that user can choose different timeout values per operation.

Improvement  #3.

Please get rid of dependency of PyU4V.conf as this can be optional for enterprise provisioning. When user deletes the file PyU4V.conf and passes required params to rest_univmax. Call fails with file config dependency.

Many Thanks.

**Comment by ciarams87** [comment]
Thanks @mallilinux1978, I will make these improvements

**Comment by ciarams87** [comment]
New version released, hopefully the revisions meet your needs. Thanks for your feedback, Ciara
