### ISSUE TITLE
Help needed to check progress of a restore Operation.

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#104]
Hi,
I am using PyU4V= 9.1.3.0.
I am Performing a restore operation on a Storage group and while doing so, i am get restore State as In-Progress.
How do i check or wait for the job and get it as 'Restored'.
Following is the snippet i tried:
`
from contextlib import contextmanager
>>> @contextmanager
... def get_session():
...  try:
...   conn = PyU4V.U4VConn(username=username, password=password, server_ip=server_ip, port=port, verify=False, array_id = array_id)
...   yield conn
...  except Exception as err:
...   print("Error: ", err)
...  finally:
...   conn.close_session()
`

`
with get_session() as conn:
...  restore = conn.replication.restore_snapshot("SG_OFR730_08_3", "NB16044935300836535979", gen_num=0)
...  print(restore)
`
`
{'isRestored': True, 'state': ['Established', 'RestoreInProg'], 'generation': 0, 'numStorageGroupVolumes': 1, 'sourceVolume': [{'capacity_gb': 20.00061, 'name': '000FA', 'capacity': 10923}], 'tracks': 19247, 'timestamp': '18:09:18 Wed, 04 Nov 2020 IST +0530', 'name': 'NB16044935300836535979', 'linked_storage_group_names': ['NB16044935300836535979-export'], 'numSourceVolumes': 1, 'linkedStorageGroup': [{'trackSize': 131072, 'linkedCreationTimestamp': '18:12:59 Wed, 04 Nov 2020 IST +0530', 'percentageCopied': 0, 'source_volume_name': '000FA', 'linked_volume_name': '00105', 'tracks': 163845, 'name': 'NB16044935300836535979-export'}], 'isExpired': False, 'nonSharedTracks': 0, 'numSharedTracks': 19247, 'isLinked': True, 'numUniqueTracks': 0, 'timeToLiveExpiryDate': 'N/A'}`

1. How can i fetch the Restore status for this Operation.[**RestoreInProg**]
I went through the test examples, https://github.com/dell/PyU4V/blob/master/PyU4V/tests/ci_tests/test_pyu4v_ci_replication.py#L261
But these fetch the states as 'Restored' upon executing the restore request.

2. Does the above conn.close_session() the way to end an active session or do we need to invalidate cookies or something for the same ?

3. as the close session is called just after executing the restore request and the operation is in progress what impact would it have on an ongoing rest session.

**Comment by rawstorage** [comment]
HI,
you don't need to wait for the restore to complete before the data is available.  This is a long standing feature of our replication technologies.  

The session will take some time to transition into a restored state and you can check this using the replication function get_snapshot_generation_details.

closing a session is enough to end your active session with conn.close_session()  

Closing the session has no impact on the restore, the restore is executed in the microcode of the array.

**Comment by mukeshguptakc** [comment]
Thank you, @rawstorage.
