### ISSUE TITLE
"Recover" action is missing in modify_metrodr_environment operation

### ISSUE THREAD

**Issue by v-soni11** [dell/PyU4V#105]
Management UI supports, but missing in SDK. Please add

**Comment by MichaelMcAleer** [comment]
Hi,

Unisphere for PowerMax REST API does not have a corresponding 'recover' action for Metro DR environments.  The only available options are:

- establish
- suspend
- restore
- split
- failover
- failback
- update_r1
- set_mode

**Comment by MichaelMcAleer** [comment]
Fix has been submitted in https://github.com/dell/PyU4V/pull/108, it will be merged to master when it passes review and gets clean CI overnight

**Comment by MichaelMcAleer** [comment]
This fix has been merged to master, 'recover' option is available in PyU4V 9.2.0.4
