### ISSUE TITLE
Appreciation Post

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#112]
I would like to thank you for all your efforts in providing resolution, references, documents,  not just these, but doing all in record turnaround time.

Our Team at Veritas Technologies LLC were exploring way to qualify support for DELL EMC PowerMax and VMAX array.
and we came across PyU4V SDK (https://pyu4v.readthedocs.io/en/latest/) and while trying out the REST APIs we had few queries as follows:
`1. Can we a create a new storage group or a volume from a storage group snapshot:` https://github.com/dell/PyU4V/issues/95
`2. Can we attach/map a storage group snapshot to any host:` https://github.com/dell/PyU4V/issues/96
`3. Restore a volume in a storage group from storage group snapshot: `https://github.com/dell/PyU4V/issues/97
`4. Help needed to check progress of a restore Operation.:` https://github.com/dell/PyU4V/issues/104
`5. Help needed to understand Copy session Target device.:` https://github.com/dell/PyU4V/discussions/107 

Looks like the last thread is just a query about different sessions, but has the most responses to address the concern we had.

I sincerely appreciate the time and attention you folks devoted @rawstorage @helenwalsh @MichaelMcAleer 
by providing references to test examples, documentation.

Best Regards,
Mukesh Gupta.

**Comment by rawstorage** [comment]
Mukesh, thankyou for the feedback, it's always good to hear the positives, glad we are able to help.
