### ISSUE TITLE
Installation of 9.2.0.x fails for Python 3.9.1

### ISSUE THREAD

**Issue by ktelep** [dell/PyU4V#115]
Appears that Python 3.9.1 is the latest stable release and is the default download for Windows from python.org.   Looks like setup.py just needs to be inclusive of 3.9.1, as this change on my system works, but didn't know what additional testing may need to be done before this update is made to the package as a whole.

It appears the addition of python_requires to setup.py is the culprit, and why pip installs 9.1.0.5 as default for Python 3.9.1 installs.

**Comment by helenwalsh** [comment]
Thank you for bringing this to our attention.  It may not factor the patch number in the following line

python_requires='>=3.6, <=3.9',

We will look into this.
Kind regards,
Helen

**Comment by helenwalsh** [comment]
This has been fixed in PyU4V 9.2.0.7.  Please let us know if you have any further issues.  Thank you.
