### ISSUE TITLE
rest_univmax2.py

### ISSUE THREAD

**Issue by nimeob** [dell/PyU4V#12]
Line 636 and 637 need to be
```
return self.create_resource(self.array_id, SLOPROVISIONING,
                                    'hostgroup', new_ig_data)
```
instead of
```
return self.create_resource(self.array_id, SLOPROVISIONING,
                                    'host', new_ig_data)
```
You don't create a host. You create a hostgroup.

**Comment by nimeob** [comment]
Also Line 1424 needs to be
`return self.modify_resource(
            self.array_id, SLOPROVISIONING, 'storagegroup', edit_sg_data,
            version=None, resource_name=sg_id)`
instead of
`return self.modify_resource(
            self.array_id, SLOPROVISIONING, 'host', edit_sg_data,
            version='', resource_name=sg_id)`

There are two errors in this line

**Comment by ciarams87** [comment]
Thanks @nimeob, I will update these

**Comment by ciarams87** [comment]
Thanks @nimeob for highlighting and fixing these! Ciara.
