### ISSUE TITLE
Help needed for IPv6 Fetching of Unipshere APIs

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#122]
Hello,
Currently, we are using PyU4V 9.2.1.2.

I am trying to fetch the REST API version using the IPv6 configured with Unipshere.

I am able to  get Unipshere REST API version using for Ipv4:
`https://{unisphere_ip}:8443/univmax/restapi/version`

But it fails when we access with Ipv6:  as unreachable
`'https://{server_ip}:{port}/univmax/restapi/version'.format(server_ip=self._server_ip, port=self._port)`

The Ipv6 Unisphere console is accessible through:
`https://[Unisphere_IPv6_IP]:5480/vappmgr/#/login`

Using Unisphere port and getting REST Documents or version ain't working when we do following:
`https://[Unisphere_IPv6_IP]:5480/univmax/restapi/version`

So, if want to configure using PyU4V SDK with Unipshere configured with IPv6 what we need to handle explicitly to make the SDK work with Unipshere:
```
conn = PyU4V.U4VConn(
                username=self._username, password=self._password, server_ip=
                self._server_ip, port=self._port, verify=self._verify,
                array_id=self._array_id)
```

Can you please also share any documents tests related to IPv6 usecase that we need to handle.

**Comment by helenwalsh** [comment]
Hi Mukesh, we will investigate Unisphere using IPV6.  It is not something we have tested to date using PyU4V

**Comment by rawstorage** [comment]
Mukesh, is the unsiphere console available through https://[Unisphere_IPv6_IP]:8443/univmax/

also can you try port 8443, not 5480 5480 is the vapp manager

https://[Unisphere_IPv6_IP]:8443/univmax/restapi/version

**Comment by mukeshguptakc** [comment]
Hi @rawstorage 

Thanks, for confirming the Unipshere Port.
Yes, for IPv4 we are using the Unipshere port as 8443 and that worked for us.

we just wanted to know while calling the Pyu4V object for IPv6

the server_ip would be 
```
server_ip=[server_ip]
or
server_ip = server_ip
```

 Does the PyU4V needs any handling for IPv6 or we can directly pass the way we do it for IPv4
```
conn = PyU4V.U4VConn(
                username=self._username, password=self._password, server_ip=
                self._server_ip, port=self._port, verify=self._verify,
                array_id=self._array_id)
```

**Comment by helenwalsh** [comment]
Hi Mukesh,
It should be without the square brackets.

server_ip=server_ip
port=<port of u4p>

**Comment by mukeshguptakc** [comment]
Thanks, @helenwalsh.
