### ISSUE TITLE
Discussion Help needed on unlinking snapshot

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#123]
Hello,

we are currently using PyU4V 9.2.1.2.

I have query on unlinking snapshot by snapid:
**I want to know is there a way from which i can find the linked storage group or atleast clean_up these snapshots that are linked.**

We are able to fetch the snapshot info:
```
conn.replication.get_snapshot_snap_id_details("SG_Mukesh_STG-3","snapc0716de6", "132778281731")
{'name': 'snapc0716de6', 'snapid': 132778281731, 'timestamp': '12:43:52 Sun, 21 Mar 2021 +0000', 'timestamp_utc': 1616330632000, 'state': ['Established'], 'num_source_volumes': 1, 'source_volume': [{'name': '003C4', 'capacity': 10923, 'capacity_gb': 20.00061}], 'num_storage_group_volumes': 5, 'tracks': 0, 'non_shared_tracks': 0, 'expired': False, 'linked': True, 'restored': False}
```

```
conn.replication.get_snapshot_snap_id_details("SG_Mukesh_STG-2", "snap027b6202", "132777053445")
{'name': 'snap027b6202', 'snapid': 132777053445, 'timestamp': '12:03:53 Sun, 21 Mar 2021 +0000', 'timestamp_utc': 1616328233000, 'state': ['Established'], 'num_source_volumes': 5, 'source_volume': [{'name': '003BF', 'capacity': 10923, 'capacity_gb': 20.00061}, {'name': '003C0', 'capacity': 10923, 'capacity_gb': 20.00061}, {'name': '003C1', 'capacity': 10923, 'capacity_gb': 20.00061}, {'name': '003C2', 'capacity': 10923, 'capacity_gb': 20.00061}, {'name': '003C3', 'capacity': 10923, 'capacity_gb': 20.00061}], 'num_storage_group_volumes': 5, 'tracks': 0, 'non_shared_tracks': 0, 'expired': False, 'linked': True, 'restored': False}
```

But i am unable to find to which storage group it is linked.
Based on using same name when we link i tried the following:
```
cleanup_link_storage_group: src_sg:SG_Mukesh_STG-2 export_sg: SG_snap027b6202_export snapshot_name: snap027b6202snapshot_id: 132777053445, masking_view: None
Unable to fetch session: Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is 500 and the message is {'message': 'A problem occurred modifying the snapshot snapid resource: The number of source and target devices must be equal'}.
```

In Few response of snapshot details i am able to fetch `linked_storage_group_names`.

and also ` linked_storage_group` when we perform link_by_snapshot.

I want to know is there a way from which i can find the linked storage group or atleast clean_up these snapshots that are linked.

**Comment by rawstorage** [comment]
Mukesh, I have an enhancement filed for this, unfortunately the current API doesn't have a filter to pick out the linked storage groups easily.  I've been controlling this myself with naming conventions which make it easier.  Once it's in the API it will be in  PyU4V

**Comment by mukeshguptakc** [comment]
Thanks, Paul.

is there a way to delete the linked snapshots ?
Using the source storage group and snap name and snapid.

**Comment by rawstorage** [comment]
yes,  you need to unlink first then you can terminate the snapshot.  If there is a time to live set and it has expired,  the snapshot will automatically get terminated as soon as the unlink is executed.

**Comment by rawstorage** [comment]
The two functions you need are 
unlink_snapshot_by_snap_id
delete_storage_group_snapshot_by_snap_id
