### ISSUE TITLE
Setting verify to False not ignore the SSL

### ISSUE THREAD

**Issue by lafada** [dell/PyU4V#125]
I am trying to get bypass SSL by passing `verify=False` but it still try to validate SSL.

```python
conn = U4VConn(
    username=username,
    password=password,
    server_ip=address,
    port='8443',
    verify=False,
    array_id=array_id)
conn.common.get_uni_version()
The GET request to URL https://X.X.X.X:8443/univmax/restapi/84/system/version timed-out, but may have been successful. Please check the array. Exception received: HTTPSConnectionPool(host='10.17.19.200', port=8443): Max retries exceeded with url: /univmax/restapi/84/system/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)'))).
```

How can I disable SSL or Pass certs to this method ?

**Comment by lafada** [comment]
@rawstorage can you check this when you get time ?

**Comment by rawstorage** [comment]
I'll have a look can you let me know version of pyu4v and also Unisphere?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by lafada** [comment]
@rawstorage PyU4V is latest [`9.2.1.3`](https://pypi.org/project/PyU4V/9.2.1.3/) and Unisphere version is `{"version":"V9.2.1.6"}`.

I also found the issue in `requests` (https://github.com/psf/requests/issues/3829) which is related to this. Where setting `session.verify` not ignore the SSL.

**Comment by lafada** [comment]
@rawstorage I am planing to do like below code 

```python
In [2]: import requests
   ...: class WrappedSession(requests.Session):
   ...:     """A wrapper for requests.Session to override 'verify' property, ignoring REQUESTS_CA_BUNDLE environment va
   ...: riable.
   ...:
   ...:     This is a workaround for https://github.com/kennethreitz/requests/issues/3829 (will be fixed in requests 3.
   ...: 0.0)
   ...:     """
   ...:     def merge_environment_settings(self, url, proxies, stream, verify, *args, **kwargs):
   ...:         if self.verify is False:
   ...:             verify = False
   ...:
   ...:         return super(WrappedSession, self).merge_environment_settings(url, proxies, stream, verify, *args, **kw
   ...: args)
   ...:
   ...: requests.sessions.Session = WrappedSession
In [3]: from PyU4V import U4VConn
   ...: from PyU4V.utils.exception import PyU4VException
   ...: conn = U4VConn(
   ...:         username=username,
   ...:         password=password,
   ...:         server_ip=address,
   ...:         port='8443',
   ...:         verify=False,
   ...:         array_id=uid)
In [4]: conn.common.get_uni_version()
Out[4]: ('V9.2.1.6', '92')
```

But if you think, we might get fix for this quickly, then I don't want to change my code base.

**Comment by rawstorage** [comment]
@lafada I am not seeing this issue in any of our CI Testing or when running manually.

import PyU4V

REST=PyU4V.U4VConn(username='secretuser', password='notyourbusiness',
                               server_ip='IPaddress', verify=False,
                               array_id='000297600111')

print (REST.common.get_uni_version())

"C:\Program Files\Python38\python.exe" C:/Users/rawstorage/AppData/Roaming/JetBrains/PyCharm2021.1/scratches/scratch_1.py
('V9.2.1.1', '92')

Process finished with exit code 0

I'm running PyU4V latest, urllib3 v1.26.3, requests v2.25.1 and requests-toolbelt 2.25.1 Python Interpreter on my test machine is 3.8 however our CI system checks multiple versions.  Can you try the code snippet above ?

**Comment by helenwalsh** [comment]
Apologies if I am stating the obvious but are your configuration options in PyU4V.conf one of
verify=False or verify=<path to cert>.  If there is something wrong here we need to look at our error handling

Paul's script above will prove that the False option is working

Consult the following to enable SSL
https://pyu4v.readthedocs.io/en/latest/configuration.html

[setup]
username=*****
password=*****
server_ip=xx.xx.xx.xx
port=8443
array=000XXXXXXXXX
verify=False

# This is commented out, here as an example of path to cert
#verify=/opt/stack/u4p_ca_cert.pem

**Comment by lafada** [comment]
@rawstorage are you talking about to try this ?

```python
import PyU4V

REST=PyU4V.U4VConn(username='secretuser', password='notyourbusiness',
server_ip='IPaddress', verify=False,
array_id='000297600111')

print (REST.common.get_uni_version())
```

What I tried is `rest_client.py` has session settings as https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L69-L78. I tried same base code, see below

```python
import requests
session = requests.session()

headers = {'content-type': 'application/json',
 'accept': 'application/json',
 'user-agent': 'PyU4V/9.2.1.3 (Linux; version 3.10.0-957.27.2.el7.x86_64) Python 3.7.3',
 'application-type': 'PyU4V-9.2.1.3'}
session.headers = headers

username = "username"
password = "password"
session.auth = HTTPBasicAuth(username, password)

session.verify = False
url = 'https://X.X.X.X:8443/univmax/restapi/version'

session.request(method='GET', url=url)
---------------------------------------------------------------------------
SSLCertVerificationError                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    705                 headers=headers,
--> 706                 chunked=chunked,
    707             )

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    381         try:
--> 382             self._validate_conn(conn)
    383         except (SocketTimeout, BaseSSLError) as e:

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1010             conn.connect()
   1011

/usr/local/lib/python3.7/dist-packages/urllib3/connection.py in connect(self)
    420             ssl_context=context,
--> 421             tls_in_tls=tls_in_tls,
    422         )

/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    431     else:
--> 432         ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
    433     return ssl_sock

/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    473     else:
--> 474         return ssl_context.wrap_socket(sock)

/usr/lib/python3.7/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    411             context=self,
--> 412             session=session
    413         )

/usr/lib/python3.7/ssl.py in _create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
    852                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 853                     self.do_handshake()
    854             except (OSError, ValueError):

/usr/lib/python3.7/ssl.py in do_handshake(self, block)
   1116                 self.settimeout(None)
-> 1117             self._sslobj.do_handshake()
   1118         finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    755             retries = retries.increment(
--> 756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    757             )

/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    573         if new_retry.is_exhausted():
--> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    575

MaxRetryError: HTTPSConnectionPool(host='X.X.X.X', port=8443): Max retries exceeded with url: /univmax/restapi/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-61-d1c0089b962c> in <module>
----> 1 session.request(method='GET', url=url)

/usr/local/lib/python3.7/dist-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    540         }
    541         send_kwargs.update(settings)
--> 542         resp = self.send(prep, **send_kwargs)
    543
    544         return resp

/usr/local/lib/python3.7/dist-packages/requests/sessions.py in send(self, request, **kwargs)
    653
    654         # Send the request
--> 655         r = adapter.send(request, **kwargs)
    656
    657         # Total elapsed time of the request (approximately)

/usr/local/lib/python3.7/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515
    516             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='X.X.X.X', port=8443): Max retries exceeded with url: /univmax/restapi/version (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)')))
```

The point is, when you [`session.verify`](https://github.com/psf/requests/blob/master/requests/sessions.py#L397), its not pass that value to [`request`](https://github.com/psf/requests/blob/master/requests/sessions.py#L470-L473), `request` method has `verify` variable which will be used in [`merge_environment_variable`](https://github.com/psf/requests/blob/master/requests/sessions.py#L532-L534).

Can you please check your Unisphere is SSL enabled? How I check mine is, I tried `curl https://X.X.X.X:8443/univmax/restapi/version -u $USER:$PASS` when it failed with SSL error, means its SSL enabled. If you get SSL error, then try using the above code sample.

If you check https://github.com/psf/requests/issues/3829, it says same thing, like `session.verify` not pass `verify=False` in `session.request` method.

**Comment by lafada** [comment]
@helenwalsh I am not giving any configuration, I am passing `verify=False` in my connection parameter.

**Comment by rawstorage** [comment]
my test runs no issues

[root@ansible ~]# curl https://ipaddress:8443/univmax/restapi/version -u $USER:$PASS
curl: (60) Issuer certificate is invalid.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

I've tried a few unipshere setups windows and linux and don't have this problem.  can you try a different environment as It's not reproducable in our lab.

cat test.py
from PyU4V import U4VConn

conn = U4VConn(
    username='smc',
    password='smc',
    server_ip='ipaddress',
    port='8443',
    verify=False)
print(conn.common.get_uni_version())

I'm running your script and mine which are basically similar and no issues, I just have a print in the file to output the call 
[root@ansible ~]# python3 test.py
No array id specified. Please set array ID using U4VConn.set_array_id(array_id).
('V9.2.1.1', '92')

[root@ansible ~]# python3
Python 3.6.8 (default, May  6 2020, 12:04:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.

I've anonymised my IP here.

**Comment by lafada** [comment]
@rawstorage can you show in code, like requests or PyU4V, when you pass `verify=False` it actually use that `False` value when you do `session.request` method call ?

I check the `requests.sessions.Session` code, and I also send the links in my last questions, where its not using `session.verify` to `session.request` method. I just want to see how it works in your scenario.

**Comment by rawstorage** [comment]
I can run-through the debugger Monday. And send some screenshot
________________________________

**Comment by lafada** [comment]
thanks

**Comment by lafada** [comment]
I just want to show you what my findings are

PyU4V create `rest_client` variable at https://github.com/dell/PyU4V/blob/master/PyU4V/univmax_conn.py#L111-L114, where `self.request = self.rest_client.rest_request`. 

We pass `verify=False` in the `self.rest_client = RestRequests(username, password, verify, base_url, interval, retries, application_type)`, when we check use of `verify` in `RestRequest` it set at https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L58 as `self.verify_ssl = verify` and at the last line of `__init__` it will call [`self.session = self.establish_rest_session()`](https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L67) and it will set [`session.verify = self.verify_ssl`](https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L77), means we set `self.session.verify=False` when we pass `verify=False` in `U4VConn`.

When `__init__` methods last line call for [`self.validate_unisphere()`](https://github.com/dell/PyU4V/blob/master/PyU4V/univmax_conn.py#L130) it call [`get_uni_version`](https://github.com/dell/PyU4V/blob/cf98986f8e55c0e9f746512de9d5094b48c3d404/PyU4V/univmax_conn.py#L164), and it call [`response = self.get_resource(category=VERSION, no_version=True)`](https://github.com/dell/PyU4V/blob/cf98986f8e55c0e9f746512de9d5094b48c3d404/PyU4V/common.py#L589), and it call [`self.get_request(target_uri, resource_type, kwargs.get('params'))`](https://github.com/dell/PyU4V/blob/cf98986f8e55c0e9f746512de9d5094b48c3d404/PyU4V/common.py#L375), and it call [`message, sc = self.request(target_uri, GET, params=params)`](https://github.com/dell/PyU4V/blob/cf98986f8e55c0e9f746512de9d5094b48c3d404/PyU4V/common.py#L347) where there is no mention of `self.session.verify` now, `self.request` is actually `self.session.request` method, which is actual [`requests.session.Session.request`](https://github.com/psf/requests/blob/master/requests/sessions.py#L470-L544) method call. If you go through this method, there is no use of `self.verify`, means when we set `session.verify` it will be not used in `def requests` method.

This is my analysis, I might be missing something, but I am facing this.

**Comment by helenwalsh** [comment]
Hi,
I ran the debugger through our PyU4V code and traced the verify value and performed 3 tests
1. verify = False
2. verify = <valid cert>
3. verify = <misspelt cert>

The results were as expected.  The first 2 tests succeeded and the 3rd failed with the following error 
"Could not find a suitable TLS CA certificate bundle, invalid path: ca_cert_10_69.pem"

This code is not new to this version of PyU4V and we have not seen an issue with it to date.  I am just wondering if there is something in your environment that is unearthing a bug.  Perhaps we could have a meeting to see what is different?

**Comment by helenwalsh** [comment]
the brackets remove the examples

1. verify = False
2. verify = my_valid_cert
3. verify = my_misspelt_cert

**Comment by lafada** [comment]
yes, I agree, @helenwalsh but can you check where the `verify=False` use in `requests.sessions.Session.request` method ? Let me know the suitable channel to meet.

**Comment by helenwalsh** [comment]
Hi,
Yes, everything checked out with the verify parameter in the 3 use cases above.  I have had another look over your code snippet above, we can discuss at the meeting.

**Comment by lafada** [comment]
yes, I agree, it work on you environment, but I am talking about `requests`, because requests has issue https://github.com/psf/requests/issues/3829, which says `session.verify` not use in `sessions.Session.request` method, and I am curious how it not effect `PyU4V`.

**Comment by lafada** [comment]
got it, @helenwalsh somewhere it set `REQUESTS_CA_BUNDLE` and that cause the issue :)

**Comment by lafada** [comment]
Thanks for your help @helenwalsh and @rawstorage

**Comment by lafada** [comment]
now, I am setting `REQUESTS_CA_BUNDLE` as `''` and that means it will not use those path, but the problem still exists. Try to set `REQUESTS_CA_BUNDLE` and set `verify=False` and see the magic :)

**Comment by helenwalsh** [comment]
Hi,
Interesting!  One we have not come across before.  Thank you for persisting.  Out of curiosity did you try with a valid cert?

**Comment by lafada** [comment]
@helenwalsh yes, with valid certs its working.
