### ISSUE TITLE
add only on flags to create host

### ISSUE THREAD

**Issue by caribou90** [dell/PyU4V#127]
Hello
is it possible to add flags to create a host without complet all flags item. ?Now its mandatory to selected each flags but for us only the flag "consistent_lun" is necesary.

When we try we had a INVALID :
INVALID : 
{"hostId":"toto","hostFlags":{"volume_set_addressing":{"enabled":,"override":},"disable_q_reset_on_ua":{"enabled":,"override":},"environ_set":{"enabled":,"override":},"avoid_reset_broadcast":{"enabled":,"override":},"openvms":{"enabled":,"override":},"scsi_3":{"enabled":,"override":},"spc2_protocol_version":{"enabled":,"override":},"scsi_support1":{"enabled":,"override":},"consistent_lun":true}}

**Comment by rawstorage** [comment]
unfortunately you need to supply all this is a "feature of the API" not a restriction of PyU4V.   You could do something like we've done here and create a dictionary of base flags you can reference and update.
 https://github.com/rawstorage/dellemcpmax_ansible/blob/ccb7ba0ea1461c1398378ebf24037dabcabf5049/dellemc/dellemc_pmax_host.py#L221
