### ISSUE TITLE
REST Session Timeout not behaving as expected

### ISSUE THREAD

**Issue by MichaelMcAleer** [dell/PyU4V#130]
During development of PyU4V features breakpoints were added to Unisphere to investigate server side actions during calls. 

It was noticed that instead of timing out after 120 seconds by default as set [here](https://github.com/dell/PyU4V/blob/19592e624713f46d9c61fe8feab65b1df90a7dd7/PyU4V/rest_requests.py#L50) and returning a `requests.Timeout` exception, an erroneous `PyU4V.utils.exception.VolumeBackendAPIException` was raised instead with a very misleading error message:

`PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error GET Array. The status code received is None and the message is None.`

This should be fixed asap, we gracefully handle timeouts and respond with a suitable message [here](https://github.com/dell/PyU4V/blob/19592e624713f46d9c61fe8feab65b1df90a7dd7/PyU4V/rest_requests.py#L129)

It may be PyU4V related issue, it could be a requests related issue, but given the extent to which requests is used globally I would assume that its something to do with PyU4V.

**Comment by helenwalsh** [comment]
Thanks Michael.  We will take a look at this.
