### ISSUE TITLE
Please add force option to functions

### ISSUE THREAD

**Issue by tomaszajpt** [dell/PyU4V#131]
Please add force and symforce option to functions. I'm using pyU4V for create/delete snapshot generations and when someone add new disk to storage group, then delete generations fail without force options.

Fix is simple, just add params to call self.delete_resource in delete_storage_group_snapshot method.
''
            object_type=GENERATION, object_type_id=str(gen),**params={'force': force})**
''

Thank you,

Regards,
Tomas

**Comment by rawstorage** [comment]
Hi Tomas,  we can look at adding this in future release.  If you need this function in the mean time you can use the method described in the doc to make a custom call,
rest =  PyU4V.U4VConn()
        rest.common.delete_resource(
            category=REPLICATION,
            resource_level=SYMMETRIX, resource_level_id=self.array_id,
            resource_type=STORAGEGROUP, resource_type_id=storage_group_id,
            resource=SNAPSHOT, resource_id=snap_name,
            object_type=GENERATION, object_type_id=str(gen), params={'force': force)

**Comment by rawstorage** [comment]
in progress.. will be available in PyU4V 10.1

**Comment by rawstorage** [comment]
added force options to replication functions for snapshots in 10.1 release in October
