### ISSUE TITLE
support 8.2 version?

### ISSUE THREAD

**Issue by kako420** [dell/PyU4V#14]
ru=PyU4V.RestFunctions(username="smc",password="smc",server_ip="xxxx",verify=False,port=8443,array_id="xxxxx",u4v_version='82')
print ru.get_symmetrix_array()
2018-01-17 16:11:00,879 - PyU4V.rest_requests - INFO - GET request to https://xxxx:8443/univmax/restapi/82/system/symmetrix has returned with a status code of: 500

tried this way as well..

ru = PyU4V.rest_functions()
ru.get_symmetrix_array()
2018-01-17 17:29:26,453 - PyU4V.rest_requests - INFO - No response received from API. Status code received is: 401
2018-01-17 17:29:26,453 - PyU4V.rest_requests - INFO - GET request to https://xxx:8443/univmax/restapi/system/symmetrix has returned with a status code of: 401

**Comment by rawstorage** [comment]
This is working as designed, if you are using version prior to 8.4 you should import the rest_functions class which is contained in rest_univmax.py function library.  This is also called out in the readme.

There were major changes in versioning at 8.4 which shipped all endpoints under /84/ version, prior to this only newly added calls were under /82 /83 etc.  This was confusing for consumers of the API so a call was made to port everything forward in the /84 version with the exception of performance which exists under restapi/performance.

**Comment by kako420** [comment]
i tried PyU4V.rest_functions() with 8.2 and got those error, will retry and update.

**Comment by rawstorage** [comment]
with rest_functions, can you try without passing a version.  

I tried the following code and it works just fine

from PyU4V import rest_univmax
ru=rest_univmax.rest_functions()

print (ru.get_symmetrix_array())

Output 
({'symmetrixId': ['000197000008', '000197800085', '000197800131', '000198701161', '000296700558'], 'num_of_symmetrix_arrays': 5, 'success': True}, 200)

Process finished with exit code 0

**Comment by kako420** [comment]
thanks, it is working fine. creating project based on this API and let you know if we see any issue.
thank you very much for this great work
