### ISSUE TITLE
Regarding support on retrieving initiators based on the alias name

### ISSUE THREAD

**Issue by Jennifer-John** [dell/PyU4V#141]
Hi team,

In reference to the initiators functionality,  is it possible to retrieve initiators based on the alias name?
Would there be any support added for the same?

I have tried to apply the alias filter on https://ip:port/univmax/restapi/90/sloprovisioning/symmetrix/id/initiator?alias='test/host' but it does not seem to return the matching initiator Id's. The corresponding SDK method get_initiator_list() returns only the initiator id's so I am unable to apply filter based on the alias.

Could you please provide any pointers on the same?
Thanks,
Jennifer

**Comment by rawstorage** [comment]
Jennifer, PyU4V is simply wrapping the API and the filters passed are those of the corresponding API call for Unipshere for PowerMax the list of initiators API call and filters are documented here 
https://developer.dell.com/apis/4458/versions/9.2/openapi.json/paths/~192~1sloprovisioning~1symmetrix~1%7BsymmetrixId%7D~1initiator/get  

It looks like alias is supported however from experience you probably need to send the ASCII equivalent for the / symbol as this is simply appended to the URL, PyU4V doesn't parse this input to that level, it's the same if your try to filter on things with + symbols

**Comment by Jennifer-John** [comment]
Thank you Paul for the response.
