### ISSUE TITLE
In provisioning.py allow specifying emulation type

### ISSUE THREAD

**Issue by travatine** [dell/PyU4V#143]
For mainframe storage I need to specify emulation CKD instead of FBA.

In these functions:
 create_storage_group
 add_new_volume_to_storage_group
a new parameter is needed to allow this.

To maintain compatibility with existing api the new parameter should have a default value of 'FBA'.

I'll open a pull request with the required changes.

**Comment by helenwalsh** [comment]
closed in pull request 148
