### ISSUE TITLE
Documentation and issue

### ISSUE THREAD

**Issue by cocampbe** [dell/PyU4V#15]
Installing version 3 does not seem to be documented. I did a pull, but had to figure out how to install it. It would be useful to have this on the main project page. 

On to my issue. I am running OL6. All RHEL6 flavors use python 2.6.6. You can enable software collections, but that has it's own set of unique obstacles. Anyway. I ran

 `python setup.py install`

That installed PyU4V, but the sample code will not work properly. It still acts like version 2. I checked the version via help() and it is version 2.

> Help on package PyU4V:
> 
> NAME
>     PyU4V - # -*- coding: utf-8 -*-
> 
> FILE
>     /usr/lib/python2.6/site-packages/PyU4V-3.0.0-py2.6.egg/PyU4V/__init__.py
> 
> PACKAGE CONTENTS
>     common
>     performance
>     provisioning
>     replication
>     rest_requests
>     rest_univmax
>     rest_univmax2
>     univmax_conn
>     utils (package)
> 
> DATA
>     __author__ = 'Dell EMC or its subsidieries'
>     __copyright__ = 'Copyright 2017 Dell EMC Inc'
>     __license__ = 'MIT'
>     __title__ = 'pyu4v'
>     __version__ = '2.0'
> 
> VERSION
>     2.0
> 
> AUTHOR
>     Dell EMC or its subsidieries

Is there something I need to add to the setup? Or is this related to my python version?

**Comment by cocampbe** [comment]
pip shows version 3 after installing via setup.

> PyU4V (3.0.0)

versus an actual pip install

> PyU4V (2.0.2.6)

**Comment by rawstorage** [comment]
court, 3.0 is a work in progress branch, the 2.2.6 branch on PiP is the one we would reccomend you use for now.   The 2.0 setup can be found on here.
https://github.com/ciarams87/PyU4V/tree/stable/2.0

**Comment by cocampbe** [comment]
That's funny!

> Version 3 will be the version maintained going forward, and we do suggest you move to this version when possible.

I will check out version 2.

**Comment by rawstorage** [comment]
Court, 
if you're just getting started maybe version 3 would be good, this will be our maintained branch in the future and to switch over function names in scripts will be updated.  

Thanks for pointing out that comment, we'll reword.  There is still some work going on around documentation and testing before we officially release this branch.

**Comment by rawstorage** [comment]
Court, I'll mark this issue as resolved since our exchange looks like you're up and running now.
