### ISSUE TITLE
Link one tdev to another tdev

### ISSUE THREAD

**Issue by Rafmoshe2500** [dell/PyU4V#152]
Hi,
I want to restore only one tdev from a storage group that contains a lot of tdevs (32 and maby more).
But i cant found a way to do that in the python library and in the rest api

The only way to do that is from the solution enabler via ssh.

I realy hope to see that function added in the next version.

Thanks.

**Comment by rawstorage** [comment]
Unfortunately you can't do this in the API right now  without using temporary storage groups. If an enhancement is made to the API we can certainly add in PyU4V

**Comment by Rafmoshe2500** [comment]
Hi,
Can you explain to me how to do that with temporary sgs?

And this something that you plan to include in the next versions of the
library?

בתאריך יום ג׳, 6 בדצמ׳ 2022, 17:05, מאת Paul Martin ‏<
***@***.***>:

**Comment by rawstorage** [comment]
Create an empty SG with no SLO and no SRP for source volume.  Add the volume you want to restore to the empty storage group, issue restore.

conn.provisioning.create_empty_storage_group(
    storage_group_id="temp_sg", SRP=None, service_level=None, workload=None)
conn.provisioning.add_existing_volume_to_storage_group(
    storage_group_id="temp_sg",vol_ids="00123")
conn.replication.restore_snapshot_by_snap_id("temp_sg",snap_name="mysnap",
                                             snap_id=00023435)

Do this with a test volume first to verify the process.
