### ISSUE TITLE
Support for proxies in requests

### ISSUE THREAD

**Issue by arthurzenika** [dell/PyU4V#153]
It would be nice to be able to configure proxies for the HTTP requests. 

Using https://requests.readthedocs.io/en/latest/user/advanced/?highlight=proxies#proxies it could be introduced on the `requests.session` object https://github.com/dell/PyU4V/blob/master/PyU4V/rest_requests.py#L69

**Comment by arthurzenika** [comment]
I've contributed a modification for the 9.2 branch since this is where my primary need comes from. Do you want the equivalent pull request for the 10.0 branch ? or on master ?

**Comment by rawstorage** [comment]
PR 155 adds this support on 10.0.18
