### ISSUE TITLE
Compression ratio details for devices

### ISSUE THREAD

**Issue by 212850a** [dell/PyU4V#163]
As far as I see it's possible to get details about compression ratio for SRP with a help of get_compressibility_report function.
But I can't find any function which would return compression ratio details for each individual device.
Is it possible to get compression ratio details for each device with a help of PyU4V?

**Comment by rawstorage** [comment]
Compression is reported on SRP or at storage group level, we can't pull for the individual devices

**Comment by 212850a** [comment]
Thanks for reply, Paul.
Is there any plans to add details about each individual device compression in PyU4V? (from symcfg output all these data is available)

**Comment by rawstorage** [comment]
Can you share the detail you are seeing, please omit any confidential data.  I can check API schema.

**Comment by 212850a** [comment]
Paul, I'm talking about output like the following - as you may see compression ratio is reported for each individual device:
```
symcfg -sid 111 list -tdev -gb
 
Symmetrix ID: 000297111111
 
Enabled Capacity (GBs) :    46292.6
Bound   Capacity (GBs) :    31696.9
 
      S Y M M E T R I X   T H I N   D E V I C E S
--------------------------------------------------------
                                          Total     Comp
        Bound      Flgs      Total      Allocated  Ratio
Sym   Pool Name    EMPT        GBs        GBs (%)
----- ------------ ---- ---------- ---------- --- ------
...
0010C -            FX.B      300.0      277.1  92  1.0:1
0010D -            FX.B      300.0      277.1  92  1.0:1
0010E -            FX.B      300.0      277.1  92  1.0:1
0010F -            FX.B      300.0      277.4  92  1.0:1
00110 -            FX.B      300.0       27.0   9  1.0:1
00111 -            F..B      300.0        0.0   0  5.3:1
00112 -            FX.B      300.0        0.0   0  4.7:1
00113 -            FX.B      300.0      153.9  51  1.0:1
00114 -            F..B      300.0        0.0   0  5.3:1
00115 -            FX.B      300.0        0.1   0  4.0:1
00116 -            FX.B      300.0        0.0   0  3.0:1
00117 -            FX.B      300.0      125.2  42  1.0:1
00118 -            F..B      300.0        0.0   0  5.3:1
00119 -            F..B      300.0        0.0   0  5.3:1
0011A -            FX.B      300.0      277.7  93  1.0:1
... 
Total                   ---------- ---------- --- ------
  GBs                      31696.9     7188.2  12
 
Legend:
Flags:  (E)mulation : A = AS400, F = FBA, 8 = CKD3380, 9 = CKD3390
         (M)ultipool : X = multi-pool allocations, . = single pool allocation
         (P)ersistent Allocs : A = All, S = Some, . = None
         S(T)atus    : B = Bound, I = Binding, U = Unbinding, A = Allocating,
                       D = Deallocating, R = Reclaiming, C = Compressing,
                       N = Uncompressing, F = FreeingAll, . = Unbound
```

**Comment by rawstorage** [comment]
The API definitely doesn't report to this level on device,   we can see unreducable data per volume if you do volume get 
{
  "volumeId": "0011C",
  "type": "RDF1+TDEV",
  "emulation": "FBA",
  "ssid": "FFFFFFFF",
  "allocated_percent": 0,
  "cap_gb": 1,
  "cap_mb": 1026,
  "cap_cyl": 547,
  "status": "Ready",
  "reserved": false,
  "pinned": false,
  "volume_identifier": "PyU4V-vol-vicebeqono",
  "wwn": "60000970000120200287533030313143",
  "encapsulated": false,
  "num_of_storage_groups": 0,
  "num_of_front_end_paths": 0,
  "rdfGroupId": [
    {
      "rdf_group_number": 33
    }
  ],
  "snapvx_source": false,
  "snapvx_target": false,
  "has_effective_wwn": false,
  "effective_wwn": "60000970000120200287533030313143",
  "mobility_id_enabled": false,
  "unreducible_data_gb": 0,
  "nguid": "02875330303131430000976000012020"
}

**Comment by rawstorage** [comment]
Closing as this is not supported in API
