### ISSUE TITLE
How to show device group (dg) content?

### ISSUE THREAD

**Issue by 212850a** [dell/PyU4V#171]
Hi,

I've got list of device groups (DG) with a help of performance.device_group_keys() function.
But can't find how to get details of each defined device group (DG) - I want to know what volumes are part of each device group defined on array. 
Any idea how to get it?

**Comment by rawstorage** [comment]
Hi Roman, 
device groups are not really supported by the API, the only call that I see is https://Unisphere:8443/univmax/restapi/100/replication/devicegroup/{deviceGroupId} GET

The response only gives you basic information about this.

{
  "name": "BOH_r2Casc_DG",
  "symmetrixId": "000197900256",
  "isValid": true,
  "isConcurrentRdf": true,
  "isCascadedRdf": true,
  "numStandards": [
    3
  ],
  "standardRdfgs": [
    8
  ],
  "standardPairStates": [
    "Consistent"
  ],
  "standardHop2PairStates": [
    "Synchronized"
  ],
  "numBcvs": [
    0
  ],
  "bcvRdfgs": [],
  "bcvPairStates": [],
  "bcvHop2PairStates": [],
  "groupType": "RDF2"
}

We have not done any DG development in PyU4V as it's typically StorageGroup managment within the API.  Sorrry can't be of more help and apologies for the long wait on response.  I missed the notification

**Comment by 212850a** [comment]
Thanks for response Paul.

Despite you don't have any function in PyU4V to get list of volumes from diskgroup it is implemented some how in Unisphere. If you go to Data Protection -> Device Groups, select any of defined device groups then it will be possible to list volume by clicking on number of devices in that group.
Any idea how it's implemented in Unisphere? 

I tried to utilize provisioning.get_volume_list() function by specifying filter like {'devicegroup':'BOH_r2Casc_DG'}, but it does not work - I get all volumes from array.

**Comment by rawstorage** [comment]
I'll have a look again today and see if there's anything I'm missing

Sent from Outlook for Android<https://aka.ms/AAb9ysg>


Internal Use - Confidential

________________________________

**Comment by rawstorage** [comment]
Roman, there are no additional ways in the API to view contents of Device Groups, they have limited use in the API and the performance details are legacy pre storage group.

**Comment by 212850a** [comment]
Paul, may be it can be implemented in future releases of PyU4V then?

**Comment by rawstorage** [comment]
Roman, this needs to be in the API before it's in PyU4V.  PyU4V can make any API call to PowerMax even if it's not coded using the custom API call described in the docs.  You will need to request this through your account team they will open an enhancement.  However I don't expect an enhancement of this nature to make it into the product, Device Groups are not used in Unisphere other than for few legacy operations, which have also moved primarily to storage groups control.  You can always ask.
