### ISSUE TITLE
Terminate a single snapshot

### ISSUE THREAD

**Issue by Jorre05** [dell/PyU4V#178]
Hi,

The API has a bulk_terminate_snapshots function that terminates all (or snapset_id_and_older) snapshots from a storage group.
Is there a function to terminate a specific snapshot?

Best,
Joris

**Comment by 212850a** [comment]
@Jorre05, I use replication.delete_storage_group_snapshot_by_snap_id(storage_group, snap_name, snap_id) function to terminate specific snapshot.

**Comment by rawstorage** [comment]
@212850a Roman thanks so much for helping on this,  @Jorre05 the bulk terminate feature is a hammer function, in case of emergency break glass.  Specifically you can use this to terminate a bunch of snapshots when you are trying to free up a lot of space from snapshots or if you are tearing down a setup..  The one Roman has suggested is the correct one.

**Comment by Jorre05** [comment]
@rawstorage Now that I have your attention, a quick question about the provisioning.delete_masking_view function. In the Gui, you have the option to delete the associated port groups. Am I correct that the provisioning.delete_masking_view function will not delete any associated port groups?

**Comment by rawstorage** [comment]
The API will only delete the masking view, you can script a lookup and loop in the associated object deletion if you did want to automate this part by using the associated functions in provisioning.py
