### ISSUE TITLE
 Create SRDF new pair for already replicated SG

### ISSUE THREAD

**Issue by 212850a** [dell/PyU4V#179]
In documentation there is example how to create SRDF for SG, but no examples I found about how to add new volume pairs into local and remote SG's after SRDF is already in place.
In Unisphere there is "Create Pairs" button under Data Protection -> SRDF Groups which does all required magic.

Can you please confirm what PyU4V functions should be run in order to add volume pairs into local and remote SG's if SRDF is already established between these SG's?

**Comment by rawstorage** [comment]
https://pyu4v.readthedocs.io/en/latest/PyU4V.html#PyU4V.provisioning.ProvisioningFunctions.add_new_volume_to_storage_group

If you use the add_new_volume_to_storage_group function in provisioning, this one has the funtionality to do the additional steps to add to any remote storage group, it also creates the new volumes as SRDF.

remote_array_1_id – 12 digit serial number of remote array, optional – str

remote_array_1_sgs – list of storage groups on remote array to add Remote device, Unisphere instance must be local to R1 storage group otherwise volumes will only be added to the local group – str or list

The function also supports concurrent SRDF.. you can specify remote_arrray_e_id and remote_array_2_sgs

**Comment by 212850a** [comment]
@rawstorage, good point - yes, we use add_new_volume_to_storage_group() function. 
Only one thing is not clear - how to pass exemption boolen to that function.
If we use SRDF/A for most SG's and try to add new volumes with a help of add_new_volume_to_storage_group() we get "The request is not allowed for SRDF/A-capable devices in async mode".

**Comment by rawstorage** [comment]
my understanding is that new volumes are automatically added with consistency exempt .  Did you try this and get an error?  I'll check the API again for additional options

**Comment by 212850a** [comment]
Yes, I've tried that and got "The request is not allowed for SRDF/A-capable devices in async mode" error.

**Comment by rawstorage** [comment]
import PyU4V

conn = PyU4V.U4VConn(
    username='smc',
    password='smc',
    server_ip='ipaddress',
    port='8443', array_id='000220200226',
    verify=False)


print(conn.provisioning.add_new_volume_to_storage_group(
    storage_group_id="rdfa_test", num_vols=1, cap_unit="GB", vol_size=1,
    remote_array_1_id='000297600841',remote_array_1_sgs="rdfa_test"))


run script..

"C:\Users\username\OneDrive - Dell Technologies\PycharmProjects\PyU4V-External\venv\Scripts\python.exe" C:\Users\username\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\scratch.py 
{'storageGroupId': 'rdfa_test', 'slo': 'Diamond', 'service_level': 'Diamond', 'base_slo_name': 'Diamond', 'srp': 'SRP_1', 'slo_compliance': 'NONE', 'num_of_vols': 3, 'num_of_child_sgs': 0, 'num_of_parent_sgs': 0, 'num_of_masking_views': 0, 'num_of_snapshots': 0, 'cap_gb': 3.0, 'device_emulation': 'FBA', 'type': 'Standalone', 'unprotected': False, 'compression': True, 'compression_ratio_to_one': 0.0, 'vp_saved_percent': 100.0, 'uuid': '600009700d1ffd2257000144000001a7', 'unreducible_data_gb': 0.0}

Process finished with exit code 0

Do you have consistency enabled on the RDFG also ?

**Comment by 212850a** [comment]
Strange, I've run again and got success. Not sure why it didn't work when I run it for the first time.
Thanks Paul again for solution.

**Comment by 212850a** [comment]
It can be closed

**Comment by rawstorage** [comment]
I just enabled consistency on my RDFG and re-ran, script worked 

"C:\Users\username\OneDrive - Dell Technologies\PycharmProjects\PyU4V-External\venv\Scripts\python.exe" C:\Users\username\AppData\Roaming\JetBrains\PyCharm2023.2\scratches\scratch.py 
{'storageGroupId': 'rdfa_test', 'slo': 'Diamond', 'service_level': 'Diamond', 'base_slo_name': 'Diamond', 'srp': 'SRP_1', 'slo_compliance': 'NONE', 'num_of_vols': 4, 'num_of_child_sgs': 0, 'num_of_parent_sgs': 0, 'num_of_masking_views': 0, 'num_of_snapshots': 0, 'cap_gb': 4.0, 'device_emulation': 'FBA', 'type': 'Standalone', 'unprotected': False, 'compression': True, 'compression_ratio_to_one': 0.0, 'vp_saved_percent': 100.0, 'uuid': '600009700d1ffd2257000144000001a7', 'unreducible_data_gb': 0.0}

Process finished with exit code 0

It added the additional volume without error so not sure why you are getting an issue.  Below is Get on RDF group and storage group 

https://ipaddress:8443/univmax/restapi/101/replication/symmetrix/000220200226/storagegroup/rdfa_test/rdf_group/5

{
  "symmetrixId": "000220200226",
  "storageGroupName": "rdfa_test",
  "rdfGroupNumber": 5,
  "volumeRdfTypes": [
    "R1"
  ],
  "states": [
    "Consistent"
  ],
  "modes": [
    "Asynchronous"
  ],
  "largerRdfSides": [
    "Equal"
  ],
  "totalTracks": 32760,
  "capacity_mb": 4096,
  "localR1InvalidTracksHop1": 0,
  "localR2InvalidTracksHop1": 0,
  "remoteR1InvalidTracksHop1": 0,
  "remoteR2InvalidTracksHop1": 0,
  "srcR1InvalidTracksHop2": 0,
  "srcR2InvalidTracksHop2": 0,
  "tgtR1InvalidTracksHop2": 0,
  "tgtR2InvalidTracksHop2": 0,
  "domino": [
    "Disabled"
  ],
  "consistency_protection": "Enabled"
}
