### ISSUE TITLE
120s Timeout results in None response. for long running commands  

### ISSUE THREAD

**Issue by rawstorage** [dell/PyU4V#180]
2024-02-15T20:32:35.673Z : level : ERROR , message : move_rdfg_devices_from_src_rdfg failed: error:Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is None and the message is None.

"/opt/XXXXXX/lib/python3.8/site-packages/PyU4V/common.py\", line 180, in check_status_code_success\n raise exception.VolumeBackendAPIException(\nPyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is None and the message is None."

**Comment by rawstorage** [comment]
Published fix for 10.1.0.2

**Comment by rawstorage** [comment]
Closed

**Comment by Sacheen123** [comment]
I am facing the same issue with 9.x version. Is there any API in 10.1.0.2 for setting up customized timeout?

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
Sacheen, this fix wasn't backported.  you have the option to review the changes in this pull request and create your own fork of the code for your own install.  

You can change the timeout in the new version in your connection string,  conn = PyU4V.U4VConn(username='smc', password='smc',  server_ip='ipaddress', verify=None,  array_id='000220200226', timeout=300) .  PyU4V 10.1 has this code and is capable of supporting older arrays, you can upgrade an external Unipshere to this code to avail of the fix.

**Comment by Sacheen123** [comment]
Thank you, Paul for your help as always.
