### ISSUE TITLE
How to know the size for each taken snapshot?

### ISSUE THREAD

**Issue by 212850a** [dell/PyU4V#182]
Hi, 
With a help of get_snapshot_snap_id_details() function we get various details about taken snapshot, but not sure how to know the size of taken snapshot. I can see only numbers for tracks and non_shared_tracks there which potentially can be used to calculate size, but not sure how to use them.

Can you please confirm how to know the size for every taken snapshot?

**Comment by rawstorage** [comment]
Roman, there are a few approaches to getting snapshot capacity, but the implementation will depend on how you intend to use.  

In general you can use the snapshot capacity numbers, the tracks can be multiplied by 128 kb to give you raw capacity numbers, the tracks is the potential space that the snapshot is consuming, non-shared tracks is the guaranteed capacity  that would be released to the array should you terminate a particular version of a snap.  There's a lot of sharing going on and data reduction with compression and deduplication so these numbers are not straightforward only guides.

If you want to mail me direct we can setup a call to discuss other options.  _paule.martin@_&*dell.com_ remove underscores and &* trying to avoid the spambots ;)

**Comment by 212850a** [comment]
Paul, in PyU4V with a help of get_snapshot_snap_id_details() we can get details about size of specific snapshot for SG in tracks. 
Question is - how to know the size of snapshot for every LUN from specific snapshot of SG?

**Comment by rawstorage** [comment]
Roman, sorry not had a chance to look at this yet. Will have a look today and get back to you this afternoon, it's on my list.  Can you confirm which version you are running?, I think we may have to use 10.1 to get the information you seek. But will run some tests later today.

**Comment by 212850a** [comment]
We use PyU4V 9.2 as most of our arrays are PMAX 2K.
From Unisphere I can get this level of details with the following steps:
Select storage group -> choose DATA PROTECTION tab -> SNAPSHOTS -> choose some of existing snapshot -> from right side opened information click on number of volumes and get list of volumes in selected snapshot. If select some volume from the list from right hand side there will be info about this specific volume in selected snapshot (included Tracks - size).

**Comment by rawstorage** [comment]
OK, definitely easy in API with 10.1
https://ipaddress:8443/univmax/rest/v1/systems/000220200226/volumes?select=snapvx_source,snapshots.id,snapshots.name,snapshots.cap_gb,snapshots.tracks&filter=snapvx_source eq true

Response for every volume with a snapshot on the system.

with PyU4V 10.1 use the volumes.get_volumes_details function and pass the filters and selection as above.  The filters are passed in as per the documentation.

{
  "volumes": [
    {
      "id": "001A2",
      "snapvx_source": true,
      "snapshots": [
        {
          "id": "61997211649",
          "name": "Veeam-UNITTEST-110211300279",
          "cap_gb": 1,
          "tracks": 0
        }
      ]
    },
    {
      "id": "001A6",
      "snapvx_source": true,
      "snapshots": [
        {
          "id": "63144324865",
          "name": "SnapshotGenerationTests",
          "cap_gb": 1,
          "tracks": 0
        },
        {
          "id": "63144323841",
          "name": "SnapshotGenerationTests",
          "cap_gb": 1,
          "tracks": 0
        },

**Comment by rawstorage** [comment]
> We use PyU4V 9.2 as most of our arrays are PMAX 2K. From Unisphere I can get this level of details with the following steps: Select storage group -> choose DATA PROTECTION tab -> SNAPSHOTS -> choose some of existing snapshot -> from right side opened information click on number of volumes and get list of volumes in selected snapshot. If select some volume from the list from right hand side there will be info about this specific volume in selected snapshot (included Tracks - size).

>>Unfortunately we can't get the individual device track usage with REST with 9.2 version of the API, only way I've been able to find is with the enhanced call shown in previous command.  Apologies for late responses

**Comment by 212850a** [comment]
Thanks for confirmation Paul.
