### ISSUE TITLE
Supportability of Python, Unispehere, requests & six package versions with PyU4V versions

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#183]
Hi,

I am from Veritas Technologies & need answer to following question:

What are supported Python, Unispehere, requests & six package versions with PyU4V versions – 3.0.0 to 3.0.0.14, 3.1.0.16 to 3.1.0.18, 3.1.2 to 3.1.7, 9.1.0.0 to 9.1.5.0.

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
We don't explicitly qualify particular versions of six, or requests packages, versions were tested with lates available.  Supported Unipshere version is called out on each package,  From Version 9.1 and higher the Major version of Unisphere should match the version of PyU4V, e.g. PyU4V 9.1.x is compatible with Unisphere 9.1.x.  Unisphere for PowerMax has backward compatibility for N-2 versioins of the API meaning version 10.1, will support API version 10.1, 10.x and 9.2 but ideally things should match for simplicity of support.

**Comment by Sacheen123** [comment]
> rawstorage

Thanks a lot friend.
