### ISSUE TITLE
Are these API's Array agnostic?

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#185]
Are these API's Array (VMAX &PoweMAX) agnostic?

Thanks,
Sacheen

**Comment by rawstorage** [comment]
For the most part yes, depending on the array model and microcode running you will get different API responses from each.  Some features will require specific models but basic provisioning and replication functions will work across all VMAX3 and PowerMax models.  A good guide if you can do it in the Unisphere UI against the array the API will behave the same. 

Performance Stats returned will also differ per array model, you should use the lookup functions in performance.py  see what categories are validor simplify using the enhanced performance modules which greatly simplify getting performance data from the arrays.

**Comment by Sacheen123** [comment]
> For the most part yes, depending on the array model and microcode running you will get different API responses from each. Some features will require specific models but basic provisioning and replication functions will work across all VMAX3 and PowerMax models. A good guide if you can do it in the Unisphere UI against the array the API will behave the same.
> 
> Performance Stats returned will also differ per array model, you should use the lookup functions in performance.py see what categories are validor simplify using the enhanced performance modules which greatly simplify getting performance data from the arrays.

Thanks A lot for your response.
