### ISSUE TITLE
Getting exception: A problem occurred modifying the Storage Group SRDF Group resource: Unable to acquire the Symmetrix device lock

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#186]
Hi,

Thank you for your help in advance.

I am calling API failover_storage_group_srdf() with failover_options {'failover': {'establish': True} } on my DR (secondary) site, but the API is throwing an exception: 
**Bad or unexpected response from the storage volume backend API: Error PUT symmetrix resource. The status code received is 500 and the message is {'message': 'A problem occurred modifying the Storage Group SRDF Group resource: Unable to acquire the Symmetrix device lock'}.**

The API is calling from node which is currently DR/secondary node & expected to change the roles. It is able to change the role but worrying about the exception.

I am not able to find any document describing options that can be passed as parameter in failover_options like bypass', 'star', 'restore', 'immediate', 'hop2', 'force', 'symForce', 'remote', 'establish'.

I then updated the failover_options in failover_storage_group_srdf() with remote as True: {'failover': {'establish': True, **'remote': True}** }

It is now not throwing an exception, but I am not sure is it ok to use remote option in here. Please help.

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
There is a configuration lock on these devices, this is not an API problem or issue with PyU4V.  https://support.dell.com/kb/61086

**Comment by rawstorage** [comment]
not a PyU4V issue

**Comment by Sacheen123** [comment]
> There is a configuration lock on these devices, this is not an API problem or issue with PyU4V. https://support.dell.com/kb/61086

Thank you very much for your reply. 
Do I need to wait for a configuration lock to release?  If yes, what is a REST API to use?
Is is ok to ignore the exception ?
Unable to url https://support.dell.com/kb/61086 

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
Sacheen,  I have no idea why these locks are on your system, if you are not confident in releasing them yourself then you should open an SR with Dell Support.  I have no idea if your system is in production etc so can't advise you on this via GitHub.  Please open a service request and a member of Technical Support will assist.

**Comment by Sacheen123** [comment]
Thank you Paul.
