### ISSUE TITLE
Bug: unable to detect correct replication  state using PyU4V

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#187]
Thanks Paul as always for your prompt reply & help.

I think I found a bug in the PyU4V 9.2.1.7
I am using a server, A & B with SRDF SG & replication between them for DR. 
The REST replication.get_storage_group_srdf_details(storage_group_id=self.group_name, rdfg_num=self.rdf_number)
is returning incorrect replication state as "Split" instead "Synchronized"
Steps 1:
#symrdf -sid 701 -sg SG_TASKV0570190_4GB_pri split
Steps 2:
#symrdf -sid 701 -sg SG_TASKV0570190_4GB_pri establish
Steps 3:
call to REST eplication.get_storage_group_srdf_details(storage_group_id=self.group_name, rdfg_num=self.rdf_number)
This call returns replication state as "Split" instead "Synchronized"

Looks like replication state is not updated on Unishere & returning old state. 
Do I need to call some other API  before fetching deatils (as in Step 3) to update Unisphere to update it's cache? 
I can't move to latest version of the PyU4V .

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
Sacheen,
if you check the UI the state probably hasn't been reflected there either, in older versions of Unisphere some API calls and UI can return the older state if actions are performed outside of the UI.  Unipshere 10.x and accompanying version of PyU4V will always return the data from the Array state vs the Object model.  It's unusual to do actions in CLI and then verify with REST, had the split/establish been done with REST you would not have seen this issue.  

Regardless the Object model from Unisphere will update within a minute, but if you need things to be 100% updated for whatever reason you can force an object model refresh by doing a small change like create an empty storage group and delete with REST.  

As stated though you won't see these issues in the newer version, also the new API has a refresh API call that can be executed every 5 minutes to avoid any corner case where object model is not refreshed.
