### ISSUE TITLE
way to find equivalent ymcli command corresponding to REST

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#188]
Thanks Paul in advance.

Is there any way to find out equivalent symcli command corresponding REST call?

I would like to know equivalent backend command for the REST call:
failover_storage_group_srdf(storage_group_id="mySG", srdf_group_number=101, failover_options=opt, _async=False)
Here,
opt = {'failover': {'establish': False} }

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
There is no direct translation from symcli to REST, there is equivalent functionality but they are not on a 1:1 basis, the reason for this is that REST is enhanced and takes advantage of automation built into Unipshere server, often things you do in symcli require multiple steps, the automation built into a lot of the API calls will do things in single step, especially in SRDF.  Think adding devices  , REST will add them to both source and target array(s) even if you are doing multi-hop and do all the pairing for you.

In this case the call you are trying to do does have a direct translation though

symrdf -sg mgsg -rdfg 101 failover 

These commands are documented in help and also in the cli user guide https://dl.dell.com/content/manual41010462-dell-solutions-enabler-10-0-0-srdf-family-cli-user-guide.pdf?language=en-us page 62
