### ISSUE TITLE
want to swap roles of replication

### ISSUE THREAD

**Issue by Sacheen123** [dell/PyU4V#189]
Hi,
I want to swap roles of replication with synchronous replication of multiple storage group using following call to the API

conn.replication.failover_storage_group_srdf(storage_group_id="abc", srdf_group_number=101, failover_options=opt, _async=False) 

Can I need to use opt = {'failover': {'establish': True, **'remote': True}** }
Can you help me to understand what is meaning of 'remote': True ? When can one use it? use cases?

Thanks,
Sacheen Birhade

**Comment by rawstorage** [comment]
https://developer.dell.com/apis/4458/versions/10.1.0/docs/Getting%20Started/1.introduction.md API documentation and CLI documentation are your friend here.

Per the Documentation Requests a remote data copy flag. When the concurrent link is ready, data is copied to the concurrent SRDF mirror. These operations require the remote data copy option, or the concurrent link to be suspended.

Unless you are using concurrent SRDF you don't need to worry about it.,
