### ISSUE TITLE
Timeout for get_masking_view_connection()

### ISSUE THREAD

**Issue by 212850a** [dell/PyU4V#204]
Hi,

We have couple of dedicated arrays where masking views contains hundreds of lines, as example:
`
> mv=a.connection.provisioning.get_masking_view_connections('MVNAME')
> len(mv)
119808
`

As result during collection job we get timeout for get_masking_view_connections() function - it returns:

`exception.VolumeBackendAPIException('PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error GET symmetrix. The status code received is None and the message is None').`

I've tried to increase timeout to 150 seconds with a help of set_requests_timeout(150) function but it didn't really help.
Sometimes it works and sometimes not. 

Is there any way to make get_masking_view_connections()function faster, may be by using some specific filters?

The reason why we use get_masking_view_connections() is we need to get list of devices with their scsi by host and looks like get_masking_view_connections() is the only one way to get list of volumes with their scsi id's. Or there is another way?

p.s. 
We use PyU4V 9.2 as we have plenty of PMAX 2k/8k still.

**Comment by rawstorage** [comment]
Hi Roman,
This message is coming from Unisphere API and not PyU4V the only thing you can do in these cases is to do a lookup after the call mate put in a wait and then look to the view to see if it has actually been created. It's worth opening a ticket to look at the Unisphere server to make sure its not overloaded with too many api calls at the time this is happening also.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>


Internal Use - Confidential

________________________________
From: Roman ***@***.***>
Sent: Tuesday, October 15, 2024 9:10:40 AM
To: dell/PyU4V ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dell/PyU4V] Timeout for get_masking_view_connection() (Issue #204)


[EXTERNAL EMAIL]

Hi,

We have couple of dedicated arrays where masking views contains hundreds of lines, as example:
`

mv=a.connection.provisioning.get_masking_view_connections('MVNAME')
len(mv)
119808
`
As result during collection job we get timeout for get_masking_view_connections() function.
it returns exception.VolumeBackendAPIException('PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error GET symmetrix. The status code received is None and the message is None').

I've tried to increase timeout to 150 seconds with a help of set_requests_timeout(150) function but it didn't really help.
Sometimes it works and sometimes not.

Is there any way to make get_masking_view_connections()function faster, may be by using some specific filters?

The reason why we use get_masking_view_connections() is we need to get list of devices with their scsi by host and looks like get_masking_view_connections() is the only one way to get list of volumes with their scsi id's. Or there is another way?

p.s.
We use PyU4V 9.2 as we have plenty of PMAX 2k/8k still.

**Comment by 212850a** [comment]
Paul, can you please give me example of code snippet which can wait and do lookup after?

**Comment by rawstorage** [comment]
job = (conn.provisioning.create_masking_view_existing_components(
    storage_group_name=SG_NAME, port_group_name=PG_NAME,
    host_group_name=HG_NAME, _async=True)

conn.common.wait_for_job_to_complete(job)
print(conn.common.get_job_by_id(job)

The above code should work, using Async job queue to execute the job and looking up with the inbuilt functions should help.


Paul Martin
Senior Principal Engineering Technologist
Dell | ISG - PowerMax and VMAX
Cell +35387 696 0621
Timezone GMT

Please note that my working days are Tuesday – Friday.

Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/

WhitePapers - https://infohub.delltechnologies.com/t/storage/



Internal Use - Confidential

**Comment by 212850a** [comment]
Thanks for suggestion, but looks like connection.provisioning.get_masking_view_connections can't be run as async job, it does not have _async option.
`
TypeError:  get_masking_view_connections() got an unexpected keyword argument '_async'
`

**Comment by rawstorage** [comment]
Sorry I misunderstood I thought you wanted to create a masking view.  Not review the masking view connections,   Presumably you are looking up the host lun address if you are using this call.  I know that call can be problematic especially if there  are a large number of initiators with multiple paths.  I believe there were fixes in later versions of Unisphere for PowerMax to make this more efficient but you would need to check with Dell support.

Paul Martin
Senior Principal Engineering Technologist
Dell | ISG - PowerMax and VMAX
Cell +35387 696 0621
Timezone GMT

Please note that my working days are Tuesday – Friday.

Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/

WhitePapers - https://infohub.delltechnologies.com/t/storage/



Internal Use - Confidential

From: Martin, Paul
Sent: Tuesday, October 15, 2024 3:57 PM
To: dell/PyU4V ***@***.***>; dell/PyU4V ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [dell/PyU4V] Timeout for get_masking_view_connection() (Issue #204)

job = (conn.provisioning.create_masking_view_existing_components(
    storage_group_name=SG_NAME, port_group_name=PG_NAME,
    host_group_name=HG_NAME, _async=True)

conn.common.wait_for_job_to_complete(job)
print(conn.common.get_job_by_id(job)

The above code should work, using Async job queue to execute the job and looking up with the inbuilt functions should help.


Paul Martin
Senior Principal Engineering Technologist
Dell | ISG - PowerMax and VMAX
Cell +35387 696 0621
Timezone GMT

Please note that my working days are Tuesday – Friday.

Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/

WhitePapers - https://infohub.delltechnologies.com/t/storage/

**Comment by rawstorage** [comment]
Closing as this is not directly an issue for PyU4V and needs to be worked with support
