### ISSUE TITLE
Logging setup

### ISSUE THREAD

**Issue by kako420** [dell/PyU4V#21]
do we have document to setup log file?
this is not a issue just need information only

i see options in config file but not able to make it work.

**Comment by ciarams87** [comment]
Hi kako420,
There is actually an issue with the logging configuration I am currently working on - I will have a fix (and appropriate documentation) uploaded in the next couple of days.
Thanks,
Ciara

**Comment by ciarams87** [comment]
Hi Kako420,
I have fixed the minor issue with the configuration file, so it should be work correctly now.

The logging can be setup any way that suits your project by entering the required parameters in the configuration file - please see https://docs.python.org/2/library/logging.config.html#logging-config-fileformat . The code will pick up any options set here.

Thanks for using PyU4V!
Ciara
