### ISSUE TITLE
Cannot delete storage group

### ISSUE THREAD

**Issue by cocampbe** [dell/PyU4V#23]
Unisphere version is 90. Getting this error on trying to delete an SG.

> PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error Delete storagegroup resource. The status code received is 500 and the message is {u'message': u'The server encountered an unexpected condition which prevented it from fulfilling the request'}.

May be possible that 84 rest calls are not working against 90. Need to do more digging.

**Comment by ghost** [comment]
There should be no issues using Unisphere REST API /84 endpoints with /90, they have been purposefully kept the same so as to not break any existing scripts which may be using them.

If you happen to see this behaviour re-occurring send over the logs associated with the operation you are trying to carry out so we can get a better look at what is going on.

**Comment by cocampbe** [comment]
I am using the defaults from the example conf file. 

 

> ; log configuration
> [loggers]
> keys=root,PyU4V
> 
> [handlers]
> keys=consoleHandler
> 
> [formatters]
> keys=simpleFormatter
> 
> [logger_root]
> level=INFO
> handlers=consoleHandler, fileHandler
> 
> [logger_PyU4V]
> level=INFO
> handlers=consoleHandler, fileHandler
> qualname=PyU4V
> propagate=0
> 
> [handler_consoleHandler]
> class=StreamHandler
> level=INFO
> formatter=simpleFormatter
> args=(sys.stdout,)
> 
> [handler_fileHandler]
> class=FileHandler
> level=INFO
> formatter=simpleFormatter
> args=(~/.PyU4V/PyU4V.log)
> 

I am not seeing the log under my home directory. I am just running the commands in IDLE at this point. Still getting the same error. I am not seeing much on logging on readthedocs.

**Comment by cocampbe** [comment]
I am running the following command.

`conn.provisioning.delete_storagegroup('TEST_SG')`

My understanding is that I only need to supply the SG name. The SG is not in a masking view. For grins I added a few print statements to common.py:

```
 print(target_uri)
 print(kwargs.get('payload'))
```

The URI is good, but the kwargs is None.

> /84/sloprovisioning/symmetrix/000197000395/storagegroup
> None
> Traceback (most recent call last):
>   File "./del_sg.py", line 7, in <module>
>     print(conn.provisioning.delete_storagegroup('TEST_SG'))
>   File "/usr/lib/python2.7/site-packages/PyU4V/provisioning.py", line 1288, in delete_storagegroup
>     self.array_id, SLOPROVISIONING, 'storagegroup', storagegroup_id)
>   File "/usr/lib/python2.7/site-packages/PyU4V/common.py", line 466, in delete_resource
>     self.check_status_code_success(operation, status_code, message)
>   File "/usr/lib/python2.7/site-packages/PyU4V/common.py", line 167, in check_status_code_success
>     data=exception_message)
> PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error Delete storagegroup resource. The status code received is 500 and the message is {u'message': u'The server encountered an unexpected condition which prevented it from fulfilling the request'}.

**Comment by cocampbe** [comment]
I resolved the issue. Code in provisioning.py:

```
 self.delete_resource(
            self.array_id, SLOPROVISIONING, 'storagegroup', storagegroup_id)
```

Changed to:

```
 self.delete_resource(
            self.array_id, SLOPROVISIONING, 'storagegroup', resource_name=storagegroup_id)
```

delete worked after adding 'resource_name='. On another note. I noticed that for almost all the delete_* functions, the 'resource_name=' is missing. Might be an issue.

**Comment by cocampbe** [comment]
Any update? Haven't heard back in a while.

**Comment by rawstorage** [comment]
Sorry Court, will have a look at this today,

**Comment by cocampbe** [comment]
No worries. Since you guys already did all the magic, I was hoping to incorporate your module into some ansible modules for VMAX. I found the VMAX rest api doc to be lacking. I couldn't figure out how to create a tdev via the docs. I then lokoed at your code and found it. So I figured, why recreate the wheel. Great module!

**Comment by rawstorage** [comment]
Court changes have been merged back into master branch, I found a few more that needed it, thanks for pointing this out.
