### ISSUE TITLE
PyU4V.conf not read in home directory

### ISSUE THREAD

**Issue by jonmetzger** [dell/PyU4V#24]
Running Python 2.7.13 on Linux, the file \~/.PyU4V/PyU4V.conf isn't parsed when initializing a new U4VConnection.  It appears tilde expansion isn't happening on line 20 of utils/config_handler.py.  It works when I change the line from global_path = os.path.normpath('\~/.PyU4V/PyU4V.conf') to global_path = os.path.expanduser('\~/.PyU4V/PyU4V.conf').

**Comment by ghost** [comment]
Hi Jon,

I have tried to replicate this but I am not seeing the same behavior. The file 'PyU4V.conf' needs to be in your working directory, maybe that was the cause of the issue you were seeing.

Closing this as non-issue.

Thanks
Michael
