### ISSUE TITLE
Unable to install PyU4V

### ISSUE THREAD

**Issue by saraop** [dell/PyU4V#26]
Hi Team, 

I am unable to install PyU4V. Getting the below error. Please assist. 

Sun 09/23/2018 19:35:25.26 C:\mydata >>>pip install PyU4V
Collecting PyU4V
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.Veri
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.Veri
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.Veri
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.Veri
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.Veri
  Could not find a version that satisfies the requirement PyU4V (from versions: )
No matching distribution found for PyU4V

Regards,
PR

**Comment by rawstorage** [comment]
Hi the problem appears to be woth the version of python you are using. Try 2.7 or 3.6

**Comment by ghost** [comment]
Hi PR,

I cannot replicate this issue on my own Windows machine. The connection error could be local to your machine or it could have been a temporary issue with PyPi. I suggest trying again and ensuring you are using the correct version of Python as indicated by Paul in the previous comment.

C:\Python27\Scripts>pip install PyU4V
Collecting PyU4V
  Downloading https://files.pythonhosted.org/packages/aa/7b/8c192faaa88e349775f694d244e2c5c261b10309d40b3e33a918aeaf603c/PyU4V-3.0.0.5-py2-none-any.whl
Collecting urllib3 (from PyU4V)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 371kB/s
Collecting six (from PyU4V)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting requests (from PyU4V)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |################################| 92kB 467kB/s
Collecting idna<2.8,>=2.5 (from requests->PyU4V)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 343kB/s
Collecting certifi>=2017.4.17 (from requests->PyU4V)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
    100% |################################| 153kB 457kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->PyU4V)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 553kB/s
Installing collected packages: urllib3, six, idna, certifi, chardet, requests, PyU4V
**Successfully installed PyU4V-3.0.0.5 certifi-2018.8.24 chardet-3.0.4 idna-2.7 requests-2.19.1 six-1.11.0 urllib3-1.23**

Thanks
Michael
