### ISSUE TITLE
split leading to SRDF failover when using modify_storagegroup_srdf 

### ISSUE THREAD

**Issue by vmaxpy** [dell/PyU4V#27]
Hi , 

In recent times i started using and i am new to PyU4V  module , when i tried to send 
 split command using this line - conn.replication.modify_storagegroup_srdf('autodr_test_r1_SG','split','9')
but its making the SG to go failed over not the split .

can you help  and let me know what am i missing ?

**Comment by ghost** [comment]
Hi There,

Aside from the examples included in the repo you can also look at my colleagues article on replication with PyU4V here: https://community.emc.com/people/PaulCork/blog/2017/02/07/unisphere-for-vmax-rest-api-examples-episode-3-return-of-the-srdf

This may be of help with your use-case, if not ask a question on the community forums :)

Michael
