### ISSUE TITLE
failed to delete masking view

### ISSUE THREAD

**Issue by tonyfts** [dell/PyU4V#28]
>>> conn.provisioning.delete_masking_view('tony_mv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/provisioning.py", line 540, in delete_masking_view
    self.array_id, SLOPROVISIONING, 'maskingview', maskingview_name)
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/common.py", line 464, in delete_resource
    self.check_status_code_success(operation, status_code, message)
  File "/usr/local/lib/python3.4/dist-packages/PyU4V/common.py", line 167, in check_status_code_success
    data=exception_message)
PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error Delete maskingview resource. The status code received is 500 and the message is {'message': 'The server encountered an unexpected condition which prevented it from fulfilling the request'}.

**Comment by ghost** [comment]
Hi Tony,

These issues are known to happen, the error code is 500 which is defined as "500 Internal Server Error is a very general HTTP status code that means something has gone wrong on the server, but the server could not be more specific on what the exact problem is."

Did you try to run the operation again, implement a retry mechanism, or check Unisphere to see if the MV was deleted? This is not specific to PyU4V as it is server side so closing this one out.

Thanks
Michael

**Comment by tonyfts** [comment]
This issue was fixed. 
Open（/usr/local/lib/python3.4/dist-packages/PyU4V/provisioning.py）file, modify following line:
      self.delete_resource(self.array_id, SLOPROVISIONING, 'maskingview', maskingview_name)
to
      self.delete_resource(self.array_id, SLOPROVISIONING, 'maskingview', resource_name=maskingview_name)

**Comment by ghost** [comment]
Thanks for the update, are you confident enough to make a pull request for the change along with a simple unit test for the change? I will merge it to master then so the fix is made permanent for all users.

**Comment by tonyfts** [comment]
Yes, I test it, and run OK.
and those functions: delete_host, delete_portgroup, delete_storagegroup also need to modify as below:

self.delete_resource(self.array_id, SLOPROVISIONING, 'maskingview', maskingview_name)
---> self.delete_resource(self.array_id, SLOPROVISIONING, 'maskingview', resource_name=maskingview_name)

self.delete_resource(self.array_id, SLOPROVISIONING, 'portgroup', portgroup_id)
---> self.delete_resource(self.array_id, SLOPROVISIONING, 'portgroup', resource_name=portgroup_id)

self.delete_resource(self.array_id, SLOPROVISIONING, 'host', host_id)
---> self.delete_resource(self.array_id, SLOPROVISIONING, 'host', resource_name=host_id)

self.delete_resource(self.array_id, SLOPROVISIONING, 'storagegroup', storagegroup_id)
---> self.delete_resource(self.array_id, SLOPROVISIONING, 'storagegroup', resource_name=storagegroup_id)

**Comment by ghost** [comment]
Ok thanks for highlighting these! I had to make some changes to how we construct our URIs in the code so these were missed. Feel free to create a pull request to apply the changes (with unit tests), if you cannot get to it I will make the change myself when I get some free time in the coming days.

**Comment by ghost** [comment]
This has been fixed and will be included in the next minor version release (3.0.0.8)
