### ISSUE TITLE
target_uri can't handle the new URL without version number.

### ISSUE THREAD

**Issue by lyutian** [dell/PyU4V#30]
https://github.com/ciarams87/PyU4V/blob/39ea3c7e5f1f5f1635a1d92cadeb60cef786c803/PyU4V/common.py#L511

Thanks Ciara for your useful lib. I just found some issues that may need to improve. 

The URL format here means that we can't use this kind URL `/sloprovisioning/symmetrix/xxx`.
Even we define `U4V_VERSION = None`, the URL `//sloprovisioning/symmetrix/xxx` can't be accepted by VMAX.

So, build URL base on `U4V_VERSION` input is necessary here I think.
Thanks a lot.

**Comment by ghost** [comment]
Hi Lyutian,

This is expected behaviour, it is advised not to use the non-versioned endpoints as they are from a version of the REST API used many moons ago, stick to /84 (default) or /90 for the most recent end-points and functionality/fixes.

Thanks
MIchael
