### ISSUE TITLE
get_volume_list

### ISSUE THREAD

**Issue by fabriba** [dell/PyU4V#33]
for vol in vol_page['result']:
                        vol_id_list.append(vol['volumeId'])

is incorrect: it should be:

for vol in vol_page:
                        vol_id_list.append(vol['volumeId'])

**Comment by ghost** [comment]
Hi Fabriba,

Just checked this,  when a call is made to the iterator the following response format is returned:

{
  "result": [
    {
      "volumeId": "003E9"
    },
    ...]
}

So the original format is correct, the result list needs to be iterated through not the vol_page response as it only contains one list.

**Comment by ghost** [comment]
Sorry, just seen where this issue stems from, the iterator call is extracting the results in advance of returning it.

**Comment by ghost** [comment]
Issue fixed, will be included in next minor version release (3.0.0.8)
