### ISSUE TITLE
request : creating a masking view in the target array along with srdf replication.

### ISSUE THREAD

**Issue by anishxv** [dell/PyU4V#37]
Hello Guys,

This is a request. 

How can I create a masking view with existing Portgroup, storage group with a new Initiator Group with supplied wwns .
Could someone please help me.

**Comment by helenwalsh** [comment]
Hi,
There is create_masking_view_existing_components method in provisioning that you can use.  Is it synchronous, asynchronous or metro replication?

**Comment by anishxv** [comment]
Planning to be acp_disk and later to async before splitting.

**Comment by rawstorage** [comment]
Anish, I just pushed a change in version 3.0.10

import PyU4V

conn=PyU4V.U4VConn(username="smc",password="smc",server_ip="192.168.1.6",
                   verify=False,port=8443,array_id="000197900111", \
                                                 u4v_version=90)


conn.replication.create_storagegroup_srdf_pairings(
    storagegroup_id="PYU4v2",remote_sid="000197600156",forceNewRdfGroup=True,
    srdfmode="AdaptiveCopyDisk", _async=True)


This should meet your needs
