### ISSUE TITLE
No handlers could be found for logger "PyU4V.rest_requests"

### ISSUE THREAD

**Issue by ravitejajyosula** [dell/PyU4V#38]
Hi 

I am facing the following issue when I use this module in playbook and run the playbook in AWX. I am able to run same via commad line like ansible-playbook plyabook.yml but when i run through awx I face this issue. 

Error:
"module_stderr": "No handlers could be found for logger \"PyU4V.rest_requests\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1558363142.15-275430186386678/AnsiballZ_dellpmax_createhost.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_dellpmax_createhost_payload_8zBOaH/__main__.py\", line 168, in <module>\n  File \"/tmp/ansible_dellpmax_createhost_payload_8zBOaH/__main__.py\", line 150, in main\n  File \"/usr/lib/python2.7/site-packages/PyU4V/provisioning.py\", line 148, in get_host_list\n    self.array_id, SLOPROVISIONING, 'host', params=filters)\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 321, in get_resource\n    return self.get_request(target_uri, resource_type, kwargs.get('params'))\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 277, in get_request\n    self.check_status_code_success(operation, sc, message)\n  File \"/usr/lib/python2.7/site-packages/PyU4V/common.py\", line 167, in check_status_code_success\n    data=exception_message)\nPyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error get host. The status code received is None and the message is None.\n",

**Comment by rawstorage** [comment]
Looks like AWX is having an issue with seeing the Unisphere host.  Best to open these issues against the Ansible module GitHub https://github.com/rawstorage/dellemcpmax_ansible .    Please open issue against the correct GitHub and I will have a look.  Wondering how you have configured AWX to pass the connection variables for the Unipshere server?

**Comment by rawstorage** [comment]
I'm setting up an AWX instance in my lab, would love to get a snippett of your playbook to see what's not happening,  if you could post would make things easier to determine what's going wrong.

**Comment by rawstorage** [comment]
Closing as being worked on dellemc_ansible github
