### ISSUE TITLE
get_fe_port_metrics parameter  [metriclist]

### ISSUE THREAD

**Issue by colinwsc** [dell/PyU4V#39]
Thanks for provide this valuable library. 

Tried to fetch performance metrics of PowerMax port and hit one issue with method get_fe_port_metrics. 

Based on parameter description, metriclist is one list.
   _:param metriclist: list of one or more metrics_
If input list like following.
   _['HostIOs','HostMBs','PercentBusy','ReadResponseTime','WriteResponseTime']_
It will report error.
  _({'message': 'Can not deserialize instance of com.emc.em.restapi.performance.dto.FePortMetric out of START_ARRAY token\n at [Source: com.emc.em.deployer.sharding.ReusableRequest$ReusableInputStream@53463775; line: 6, column: 9] (through reference chain: com.emc.em.restapi.performance.dto.FePortParam["metrics"]->java.util.ArrayList[0])'}, 400)_

After remove "[]" from line 177 of file PyU4V/performance.py like following.
                              _"metrics": metriclist,_

It works.

Is it one code issue or need change input ?

Br,
Colin

**Comment by rawstorage** [comment]
Colin,
I'll have a look at this again, could be a bug that I missed in this library, I haven't changed anything in the performance library for a while,  Performance is such a huge topic I figured putting just a few examples in there will allow customers to build upon it.  Can I ask the version of Unisphere you are using?

**Comment by colinwsc** [comment]
Rawstorage,  
The U4P is 9.1.0.974.

**Comment by MichaelMcAleer** [comment]
Hi Colin,

We cannot make changes to PyU4V for unreleased version of Unisphere. Can you confirm your Unisphere version is 9.1.x?  There are numerous changes in performance metrics from version to version so it is expected that you will run in to issues.

The only work around at present until we release PyU4V for 9.1.x support is to make the changes manually yourself.

Thanks
Michael

**Comment by MichaelMcAleer** [comment]
If you are an employee of Dell/Dell EMC can you send me an e-mail or skype message, you should find me via my name with no issues.
