### ISSUE TITLE
Post request error:

### ISSUE THREAD

**Issue by chiragadm** [dell/PyU4V#4]
Hi, 
    I am having issue running any of the example scripts. I have updated PYU4V.conf file with appropriate information (username, password, server_ip, port, array). I have also added SSL certification. 

Initially, I got an error relating to cert variable listed below. I believe, we need to add "cert=/path-to-file/uni_server.pem" in "PYU4V.conf" file instead of "verify=/path-to-file/uni_server.pem" since verify is boolean. I overcame below error by adding "cert=/path-to-file/uni_server.pem" in PYU4V.conf file.

#########################################################################
Cert Error:
$python ./Get_FE_Stats_LastHour.py
Traceback (most recent call last):
  File "./Get_FE_Stats_LastHour.py", line 38, in <module>
    ru = rest_functions()
  File "/testing/PyU4V/rest_univmax.py", line 62, in \_\_init\_\_
    cert = CFG.get('setup', 'cert')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'cert' in section: 'setup'
#########################################################################

After adding "cert=/path-to-file/uni_server.pem" in PYU4V.conf, I am receiving following error. I have performed some debugging on my own and it seems like PYU4U/rest_requests.py (rest_request) function is not returning anything. I very much appreciated any help. 

I am using python 2.7.10. 
P.S.: following error is coming rite away after I run the script.

#########################################################################
$python ./Get_FE_Stats_LastHour.py
2017-03-23 21:00:22,300 - PyU4V - ERROR - The POST request to URL https://testing.example.com:8443/univmax/restapi/performance/FEDirector/keys timed-out, but may have been successful.Please check the array. 
Traceback (most recent call last):
  File "./Get_FE_Stats_LastHour.py", line 51, in <module>
    dir_list = ru.get_fe_director_list()
  File "/testing/PyU4V/rest_univmax.py", line 1448, in get_fe_director_list
    for director in dir_response[0]['feDirectorInfo']:
TypeError: 'NoneType' object has no attribute '\_\_getitem\_\_'

**Comment by rawstorage** [comment]
The problem may be your python version. Items function which is used by these scripts requires version 3 you are on 2.7

Also verify that the array ID is set correctly in the config file and that this array if registered for performance collection with the unisphere instance you are pointing against.

Note array ID requires all preceeding 0 in the serial, so don't shorten like yoiu would with CLI

Sent from my Samsung device


-------- Original message --------

**Comment by chiragadm** [comment]
Hi,
   Thank you so much for prompt response. I have installed python 3.6.1 and ran the script. However, I am getting similar error. It is listed below. Following is my PYU4V.conf file.

#########################################################################
[setup]
; enter the below details - mandatory
;(can be passed as parameters on initialisation also)
username=smc
password=somepassword
server_ip=testing.example.com
port=8443
array=000196701234
; set if required, otherwise leave as is
verify=False
cert=/testing/testing.example.com.pem

; log configuration
[loggers]
keys=root,PyU4V

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_PyU4V]
level=DEBUG
handlers=consoleHandler
qualname=PyU4V
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
#########################################################################

Following is the error from script:

#########################################################################
python3 ./Get_FE_Stats_LastHour.py
2017-03-24 09:54:08,802 - PyU4V - ERROR - The POST request to URL https://testing.example.com:8443/univmax/restapi/performance/FEDirector/keys timed-out, but may have been successful.Please check the array. 
Traceback (most recent call last):
  File "./Get_FE_Stats_LastHour.py", line 51, in <module>
    dir_list = ru.get_fe_director_list()
  File "/testing/PyU4V/rest_univmax.py", line 1448, in get_fe_director_list
    for director in dir_response[0]['feDirectorInfo']:
TypeError: 'NoneType' object is not subscriptable
#########################################################################

**Comment by rawstorage** [comment]
Can you verify the version of Unisphere you are using?, I’ve tested with 8.2/8.3/8.4 although future.  Also are you 100% sure the array in question is registered for performance stats.  You can verify which arrays are registered for performance with your Unisphere server from the following endpoint via the REST client, I haven’t added this one to the github yet.

https://IPaddress:8443/univmax/restapi/performance/Array/keys

Paul Martin
Senior Principal Product Technologist

**Comment by chiragadm** [comment]
Hi,
     I am using U4V version 8.2.0.12 (It is the version that address strusts vulnerability). 
     Frame that I am querying is registered in performance. I am able to successfully query (POST) https://testing.example.com:8443/univmax/restapi/performance/FEDirector/keys using chrome/firefox browers from same host.

**Comment by chiragadm** [comment]
Hi, 
   I just wanted to let you know. I was able to resolve this issue. I had to replace "self.cert = cert" with "self.cert = None" in PyU4V/rest_requests.py  file.  

I really appreciate all the feedback.

**Comment by rawstorage** [comment]
Excellent. Glad you're back on track :)



Sent from my Samsung device


-------- Original message --------
