### ISSUE TITLE
Get volume properties

### ISSUE THREAD

**Issue by anishxv** [dell/PyU4V#40]
Hi,

Is there a way to check the "Dynamic RDF Capability" attribute set for a device using api call.

get_volume('dev_name') ; lists few properties but not the Dynamic RDF Capability.
Please suggest if you have any details on this.

**Comment by rawstorage** [comment]
All devices in VMAX3 and higher have this set by default so there is no need to check.  This library only supports VMAX3 and above so you're sorted.

**Comment by anishxv** [comment]
Thank You.
But is there a way to check the details like "Dynamic RDF Capability" for a vmax2 device.
because we are migrating data mainly from vmax2 arrays and this is needed.

Thanks in advance.

**Comment by rawstorage** [comment]
The library doesn't support VMAX 2 calls which are all under provisioning resource.
The information however should be available on this call for which there is no module pre-written.

you could use the GET call below.

/90/provisioning/symmetrix/{symmetrixId}/volume/{volumeId}

**Comment by anishxv** [comment]
ok. Thank you.
