### ISSUE TITLE
Env Check for VMAX arrays using PyU4V module.

### ISSUE THREAD

**Issue by anishxv** [dell/PyU4V#48]
Hello,

Could you please inform if there is any PyU4V function to get the env failed or Failed disks from Vmax arrays.

eg: Looking for PyU4V  options  equivalent to symcfg -sid XXXX list -env_data -service_state failed" or symdisk -sid XXX list -failed":

Thanks in advance.

**Comment by rawstorage** [comment]
Dell Customer Communication - Confidential

Abishek,
This is not currently supported in the REST modules or via REST in general in the current release 9.0.  We'll be adding some features for the next major release but will have to wait to see what the new 9.1 endpoints provide.  Keep an eye on the commits.

Paul Martin
Senior Principal Engineer
Technical marketing Engineering
DellEMC | Enterprise Software and Storage - PowerMax and VMAX
*Office +353 21 4938979
Cell +35387 696 0621
Timezone GMT


Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/


WhitePapers and Resources - http://dell.com/storageresources
https://www.dellemc.com/en-us/storage/storage-automation-and-developer-resources/index.htm


http://www.emc.com/collateral/faq/timefinder-snapvx-faqs.pdf
https://www.emc.com/collateral/technical-documentation/h13697-emc-vmax3-local-replication.pdf



[0_Specialist_Logo_-_Web,_PowerPoint,_Email][cid:image003.png@01CCA385.0F79A530]

Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by MichaelMcAleer** [comment]
Although it's not an issue I'll keep this open so we can track it in the upcoming release to see if inclusion is possible.

**Comment by rawstorage** [comment]
Abishek, this function has been added to Unisphere 9.1 released last week,  PyU4V 3.x doesn't support Unisphere 9.1 yet but we will be adding this support in the next release and the functionality will be added.
