### ISSUE TITLE
snap_data definition in rest_univmax.link_gen_snapshot redundant braces

### ISSUE THREAD

**Issue by emichaelis** [dell/PyU4V#5]
The snap_data definition in rest_univmax.link_gen_snapshot appears to be syntactically incorrect; it generates a syntax error in Python 2.6 and a type error in Python 2.7.5. The specific code is:

    snap_data = ({{"action": "Link",
                   "link": {"linkStorageGroupName": link_sg_name},
                   }})

It appears there is an extra set of braces surrounding the dictionary definition. Using this definition in Python 2.6.6 generates a syntax error:

	$ python
	Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
	[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> snap_data = ({{"action": "Link",
	...                "link": {"linkStorageGroupName": link_sg_name},
	...                }})
	  File "<stdin>", line 3
		}})
		 ^
	SyntaxError: invalid syntax
	>>>

And using this definition in 2.7.5 generates a TypeError:

	$ python
	Python 2.7.5 (default, Aug  2 2016, 04:20:16)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
	Type "help", "copyright", "credits" or "license" for more information.
	>>> link_sg_name = 'test'
	>>>
	>>> snap_data = ({{"action": "Link",
	...                "link": {"linkStorageGroupName": link_sg_name},
	...                }})
	Traceback (most recent call last):
	  File "<stdin>", line 2, in <module>
	TypeError: unhashable type: 'dict'

Removing the extra braces results in the creation of a dictionary as I would expect.

	snap_data = ({"action": "Link",
				   "link": {"linkStorageGroupName": link_sg_name},
				   })

**Comment by ciarams87** [comment]
Thank you, I will fix this.

**Comment by ciarams87** [comment]
This has been fixed
