### ISSUE TITLE
PyU4V Exception Handling Suggestions

### ISSUE THREAD

**Issue by prolly-brent** [dell/PyU4V#51]
This not an actual issue, just more of an observation with hope for suggestions.  I started using the PyU4V module a while back and quickly found it very difficult to debug my foolish mistakes.  

For example:
rjson = conn.performance.get_port_group_metrics(pg_id, start_date, end_date)

If all goes well, I get back a simple json payload which is easy to parse.  However, if I mess something up (like start/end times not in miliseconds), I get:

  File "./vmax_get_port_group_metrics.py", line 102, in <module>
    rjson = conn.performance.get_port_group_metrics(pg_id, start_date, end_date)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/PyU4V/performance.py", line 513, in get_port_group_metrics
    pg_perf_data[0]['resultList']['result'])
KeyError: 'resultList'

I can't even tell what the problem is, just that something deep below isn't happy.  What about a status_code and some response_content where I could do some real exception handling and pass along the status code and error information to the end user.  Any suggestions greatly appreciated.

Regards,
Brent

**Comment by MichaelMcAleer** [comment]
Hi Brent,

The problem above is that there is no response content "KeyError: 'resultList'" but yes I agree the exception handling in PyU4V is in need of a complete overhaul to make it more robust against various exception scenarios.

To get around the issue in your own code you can catch the KeyError Exception in your own script and determine why the port group is not returning any performance data if that is not the expected result. May I suggest the Unisphere for VMAX REST Client ([link](https://community.emc.com/docs/DOC-46344)) for running isolated calls to the REST API to determine responses while you are building out your own custom scripts, if a call for performance data for port group X in the client wont work then it wont work in PyU4V either.

The performance section in PyU4V is also going to be completely rebuilt in the next major version so it will be able to catch performance calls where no data is returned, this is expected for categories such as hosts, initiators etc.

For debugging you can use a python debugging package such as pdb or an IDE inbuilt debugger such as that found in PyCharm, I personally find the PyCharm debugger to be of great use and has a really intuitive method of going through high and low level methods.

In the mean-time I will add in a try/except in get_port_group_metrics() so no data is returned if there is a response from the REST API is received with no performance results.

**Comment by MichaelMcAleer** [comment]
Hi Brent,

A fix for the issue you are encountering has been submitted and will be cut to a new stable/3.1 branch. Keep a look out for updates to PyU4V either via the pull request or Pip.

https://github.com/MichaelMcAleer/PyU4V/pull/52

For the moment I would advise to only use the performance section for testing, there are major changes coming soon in that section which will make your life a lot easier when using PyU4V for performance metrics gathering.

**Comment by MichaelMcAleer** [comment]
An additional change is incoming momentarily if you want to hold off on updating to new code until 3.1.2 is available.

**Comment by prolly-brent** [comment]
> Hi Brent,
> 
> A fix for the issue you are encountering has been submitted and will be cut to a new stable/3.1 branch. Keep a look out for updates to PyU4V either via the pull request or Pip.
> 
> #52
> 
> For the moment I would advise to only use the performance section for testing, there are major changes coming soon in that section which will make your life a lot easier when using PyU4V for performance metrics gathering.

Great to hear Michael.  I'll probably wait for 3.1.2 release.  In the meantime I'll also try and get familiar with PyCharm.  Looking forward to the new release and I appreciate your effort on all of this.

Brent

**Comment by MichaelMcAleer** [comment]
Hi Brent, 

We found another issue in 3.1.1 so had to go to 3.1.2, I would advise updating to that version via PIP.

On the performance improvements, they will be coming in the next major release of PyU4V, just wanted to set expectations incase you assumed they were coming in 3.1.2.
