### ISSUE TITLE
Using restapi call to get the device properties (GCM).

### ISSUE THREAD

**Issue by anishxv** [dell/PyU4V#56]
I was trying for a method to see if GCM bit is set on a device or to list devices which has gcm bit is set. Does anyone know if there is an option for this please?

Thanks in advance.

**Comment by rawstorage** [comment]
Anish,
This is not possible with the API, GCM is generally only set on a very small set of devices when there is a migration between V2 and V3 using SRDF and the source volume has a uneven number of tracks that can’t align to the 128KB track size of V3 and PowerMax.  You can search for these with the cli and depending on the OS and Filesystem expand the device to be an even size to remove the GCM bit this is generally a recommended practice providing the OS using the volume can support an online volume expansion.

Please see the following technical note on the GCM bit

https://www.emc.com/collateral/technical-document/h14030-understanding-vmax3-srdf-n-1-device-compatibility-technical-note.pdf

restrictions on what can and can’t be done with GCM bit have lifted over the releases, so please check release notes for the level of PowerMax OS.  If you are running PowerMax 5978 GCM is not an issue when using NDM metro or other SRDF actions.

Regards,

Paul Martin
Senior Principal Engineer
Technical marketing Engineering
DellEMC | Enterprise Software and Storage - PowerMax and VMAX
•Office +353 21 4938979
Cell +35387 696 0621
Timezone GMT


Follow me on Twitter @rawstorage
Blog https://rawstorage.wordpress.com/


WhitePapers and Resources - http://dell.com/storageresources
https://www.dellemc.com/en-us/storage/storage-automation-and-developer-resources/index.htm


http://www.emc.com/collateral/faq/timefinder-snapvx-faqs.pdf
https://www.emc.com/collateral/technical-documentation/h13697-emc-vmax3-local-replication.pdf



[0_Specialist_Logo_-_Web,_PowerPoint,_Email][cid:image003.png@01CCA385.0F79A530]

Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.
