### ISSUE TITLE
provisioning with cyliners

### ISSUE THREAD

**Issue by mallilinux1978** [dell/PyU4V#6]
can this module support capacity provisioning using cylinders? if not can this be functionality added into this module?

**Comment by ciarams87** [comment]
Yes, this supports capacity provisioning using cylinders. On the methods 'create_non_empty_storage_group' and 'add_new_vol_to_storagegroup', simply pass in 'CYL' in for the capUnit; e.g. u4v.add_new_vol_to_storagegroup('my_sg', '2', '2000', 'CYL).
