### ISSUE TITLE
Delete SG snapshot is not working in latest PyU4V version

### ISSUE THREAD

**Issue by prashantrakheja** [dell/PyU4V#60]
This is the old PyU4V code which works (v2.0):
 
    def delete_storagegroup_snapshot(self, storagegroup, snap_name, gen_num=0):
        """Delete the snapshot of a storagegroup.
 
        :param storagegroup: the storage group name
        :param snap_name: the name of the snapshot
        :param gen_num: the generation number
        """
        resource_name = ('storagegroup/{}/snapshot/{}/generation/{}'.format(
            storagegroup, snap_name, gen_num))
        return self.delete_resource(
            self.array_id, REPLICATION, resource_name)
 
This makes a call to the following URL ->
 
DELETE
https://IP:8443/univmax/restapi/90/replication/symmetrix/000197900237/storagegroup/ansible_SG_2635/snapshot/prashant/generation/0
 
This is the latest PyU4V code which doesn’t work (v 3.1.2):
 
 
    def delete_storagegroup_snapshot(self, storagegroup, snap_name, gen_num=0):
        """Delete the snapshot of a storagegroup.
 
        :param storagegroup: the storage group name
        :param snap_name: the name of the snapshot
        :param gen_num: the generation number
        """
        resource_name = (
            '{storagegroup}/snapshot/{snap_name}/generation/{gen_num}'.format(     ISSUE is on THIS LINE
                storagegroup=storagegroup,
                snap_name=snap_name,
                gen_num=gen_num))
        return self.delete_resource(
           self.array_id, REPLICATION, resource_name)
 
 
It makes a call to the following URL:
https://IP:8443/univmax/restapi/90/replication/symmetrix/000197900237/ansible_SG_2635/snapshot/prashant/generation/0
 
^^^
Please compare this URL to the one above, notice how the keyword “storagegroup” is missing

**Comment by rawstorage** [comment]
Prashant, I've fixed that issue in PR 61, this will need to be reviewed before merging into version 3.1.3.

**Comment by prashantrakheja** [comment]
@rawstorage Great job, thank you so much

**Comment by rawstorage** [comment]
PyU4V 3.1.3 is now available on PIP
