### ISSUE TITLE
Tighter error handling when the PyU4V.conf cannot be parsed

### ISSUE THREAD

**Issue by helenwalsh** [dell/PyU4V#63]
Error received is currently 
requests.exceptions.InvalidURL: Failed to parse: https://None:None/univmax/restapi/84/sloprovisioning/symmetrix/None/maskingview

It would be great if we could catch this before it gets to the request.
Potential reasons for failure
1.  The file cannot be found
2. The tags do not exist in the file
3.  Permissions

**Comment by MichaelMcAleer** [comment]
Fix is in development, will also fix config file loading in Windows and initialising logger on Windows.

**Comment by MichaelMcAleer** [comment]
This has been addressed in https://github.com/MichaelMcAleer/PyU4V/pull/65
