### ISSUE TITLE
No array id specified. Please set array ID using the "set_array_id(array_id)" function.

### ISSUE THREAD

**Issue by AlKult** [dell/PyU4V#64]
Hi @rawstorage,

I've seen the issue https://github.com/MichaelMcAleer/PyU4V/issues/35, however I'm still experiencing the same problem.

> $ pip show PyU4V
> Name: PyU4V
> Version: 3.1.3
> Summary: A Python library for use with Dell EMC's Unisphere for VMAX RestAPI.
> Home-page: https://github.com/MichaelMcAleer/PyU4V/
> Author: Dell Inc. or its subsidiaries
> Author-email: Michael.Mcaleer@dell.com
> License: MIT
> Location: /home/foo/bar/lib/python3.6/site-packages
> Requires: six, requests, urllib3
> Required-by:

```
$ python
Python 3.6.6 (default, Aug 13 2018, 18:24:23)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyU4V
>>> PyU4V.__version__
'3.1.3'
>>> conn = PyU4V.U4VConn(username='user', password='pass', server_ip='10.11.12.13', port='8443', verify=False)
No array id specified. Please set array ID using the "set_array_id(array_id)" function.
```
I can, however, bypass the error by simply providing a dummy value for array_id:
```
>>> conn = PyU4V.U4VConn(username='user', password='pass', server_ip='10.11.12.13', port='8443', verify=False, array_id='blah')
>>> conn.common.get_uni_version()
('V8.4.0.15', '84')
>>> conn.common.get_array_list()
['000297800XXX', '000297800YYY']
```
Even though the workaround is pretty simple, I tend to think I shouldn't have to have it, therefore wondering if there's a way to rid myself of the issue.

Best regards,
Albert.

**Comment by MichaelMcAleer** [comment]
Hi Albert,

It is not an error you are seeing but a log message with warning level assigned:
```
LOG.warning('No array id specified. Please set '
                      'array ID using the "set_array_id(array_id)" '
                      'function.')
```
The message is there to let you know that there is no array ID set. It is not a requirement to have the array ID set, you can call into many functions without one or specifying your own at the time without the need of self.array_id.

There is no issue here, this is working as intended and the warning message will remain to let users know who may have mistakenly left out the array ID that they may want to set one, down to them however as their use-case may not require an array ID to be set.

If you really want to remove it, then delete the warning message and replace it with pass or something similar so any exception associated with determining self.array_id is ignored.

Thanks
Michael
