### ISSUE TITLE
extend_volume to include capacity unit variable

### ISSUE THREAD

**Issue by AlKult** [dell/PyU4V#66]
Hi,

In the `extend_volume` function, could you please make the capacity unit a variable? At current, it's hard-coded to be 'GB'.

What I've done locally and what I'm suggesting here is:
```
def extend_volume(self, device_id, new_size, cap_unit='GB', _async=False):
    """Extend a VMAX volume.

    :param device_id: volume device id
    :param new_size: the new required size for the device
    :param _async: flag to indicate if call should be async
    """
    extend_vol_payload = {'editVolumeActionParam': {
        'expandVolumeParam': {
            'volumeAttribute': {
                'volume_size': new_size,
                'capacityUnit': cap_unit}}}}
    if _async:
        extend_vol_payload.update(ASYNC_UPDATE)
    return self._modify_volume(device_id, extend_vol_payload)
```
Thanks!

Best regards,
Albert.

**Comment by MichaelMcAleer** [comment]
Hi Albert,

Thanks for getting in contact and bringing this to my attention. PyU4V version 3.1 is currently closed for enhancements, we are only accepting suggestions for security or bug fixes.

We are currently developing our next major PyU4V release and we have included this request in our list of enhancements so users can extend by cylinder, MB, GB or TB. It will be included in in the first available version of the next release.

Thanks!
Michael
