### ISSUE TITLE
Issue with header in reset_requests

### ISSUE THREAD

**Issue by rawstorage** [dell/PyU4V#68]
Ansible developers requested change due to typo in header name. _ instead of -.  Missed as this is ignored if incorrect.

**Comment by rawstorage** [comment]
Pull request 67 has fix.

**Comment by MichaelMcAleer** [comment]
Link to pull request https://github.com/MichaelMcAleer/PyU4V/pull/67

**Comment by MichaelMcAleer** [comment]
Pull request 67 merged to master, closing
