### ISSUE TITLE
Error - Compression is not supported on Symmetrix

### ISSUE THREAD

**Issue by tzcole** [dell/PyU4V#69]
I'm testing PyU4V with a newly deployed VMAX 950F AFA.  I'm able to query the UNI version and SRP, and a few other items from this array.  As it's new, it doesn't have any SGs, PGs, IGs, MVs, etc.  Using the same PyU4V version with another array I have confirmed that I'm successful at querying those things from the array including SGs, IGs, MVs, Devices, PGs, etc.  But when I try to provision a SG with a few devices, I'm getting the error shown below.  I've tried toggling 'do_disable_compression' from True to False, but I get the same error either way.

Here is my environment.
```
Python - 2.7.16
PyU4V - 3.1.5
Unisphere Version: V8.4.0.29
```

Here is the code block.
```
srp = u'SRP_1'
sg = u'sg_test'
slo = u'Diamond'
num_vols = 4
vol_size = u'72'
vol_name = u'vol_test'

res = conn.provisioning.create_storage_group(srp, sg, slo, workload=None, do_disable_comp
ression=True, num_vols=num_vols, vol_size=vol_size, cap_unit='GB', allocate_full=True, _
async=False, vol_name=vol_name)
```

```
  File "./adddevice.py", line 165, in <module>
    res = conn.provisioning.create_storage_group(srp, sg, slo, workload=None, do_disable_compression=False, num_vols=num_vols, vol_size=vol_size, cap_unit='GB', allocate_full=True, _async=False, vol_name=vol_name)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/provisioning.py", line 1036, in create_storage_group
    self.array_id, SLOPROVISIONING, 'storagegroup', payload=payload)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/common.py", line 387, in create_resource
    operation, status_code, message)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/common.py", line 172, in check_status_code_success
    data=exception_message)
PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error Create storagegroup resource. The status code received is 500 and the message is {u'message': u'A problem occurred creating the storage group resource: Compression is not supported on Symmetrix [00019xxxxxxx]'}.
```

I've tried to use this call below, but am getting the same error about "Compression is not supported..."

```
    res = conn.provisioning.create_non_empty_storagegroup(srp, sg, slo, workload=None, disable_compression=True, num_vols=num_vols, vol_size=vol_size, cap_unit='GB', _async=False)
```

It is true that the array is set for no compression, but these seems to be a bug.

**Comment by rawstorage** [comment]
Hi, can you confirm that you are able to disable compression on a storage group created within Unisphere itself.  The error suggests that the array has not been enabled for compression or the microcode level is not at a supported level.  What version of code is on the array?

**Comment by tzcole** [comment]
So this array was not sized/configured with compression.  That's why I was passing the do_disable_compression=True parameter.  I would think the library should support arrays not using compression.

We are at Hypermax OS - 5977.1131.1131

I'm also discussing the possibility of enabling compression with my CE, since there isn't a strong reason to have it disabled, but in the interim, it might be good to figure this out for others.

**Comment by rawstorage** [comment]
Ok if it's not enabled you can just skip the setting...   the default should create a group without trying to set it so you can ignore it.  Once compression is enabled on the array (online change byt the way) you can check the compression settings are on the groups or modify as necessary.

**Comment by tzcole** [comment]
So, when I remove that parameter, I'm still getting the error.

```
Traceback (most recent call last):
  File "./adddev.py", line 165, in <module>
    res = conn.provisioning.create_storage_group(srp, sg, slo, workload=None, num_vols=num_vols, vol_size=vol_size, cap_unit='GB', allocate_full=True, _async=False, vol_name=vol_name)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/provisioning.py", line 1036, in create_storage_group
    self.array_id, SLOPROVISIONING, 'storagegroup', payload=payload)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/common.py", line 387, in create_resource
    operation, status_code, message)
  File "/opt/path/python/lib/python2.7/site-packages/PyU4V/common.py", line 172, in check_status_code_success
    data=exception_message)
PyU4V.utils.exception.VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Error Create storagegroup resource. The status code received is 500 and the message is {u'message': u'A problem occurred creating the storage group resource: Compression is not supported on Symmetrix [00019xxxxxxx]'}.
```

But when I also remove allocate_full=True, then I am able to get it to work.

```
{u'cap_gb': 288.0, u'num_of_masking_views': 0, u'device_emulation': u'FBA', u'slo_compliance': u'NONE', u'storageGroupId': u'sg_test1', u'num_of_vols': 4, u'num_of_child_sgs': 0, u'num_of_parent_sgs': 0, u'VPSaved': u'100.0%', u'srp': u'SRP_1', u'slo': u'Diamond', u'unprotected': True, u'num_of_snapshots': 0, u'base_slo_name': u'Diamond', u'type': u'Standalone'}
```

Looking into the PyU4V/provisioning.py file, we can see noCompression is forced to 'true' when allocate_full is True.  I think that would need to be conditional if array compression is not enabled.

Within create_storage_group
```
            if allocate_full:
                # If case of full volume allocation, we must set the
                # noCompression parameter at true because fully
                # allocations and compression are exclusive parameters
                slo_param.update({'noCompression': 'true'})
                slo_param.update({'allocate_capacity_for_each_vol': 'true'})
                slo_param.update({'persist_preallocated_capacity_through_'
                                  'reclaim_or_copy': 'true'})
```

This change worked for me.

Within create_storage_group
```
            if allocate_full:
                # If case of full volume allocation, we must set the
                # noCompression parameter at true because fully
                # allocations and compression are exclusive parameters
                # We do this only when array compression is enabled
                if self.is_compression_capable():
                    slo_param.update({'noCompression': 'true'})

                slo_param.update({'allocate_capacity_for_each_vol': 'true'})
                slo_param.update({'persist_preallocated_capacity_through_'
                                  'reclaim_or_copy': 'true'})
```

And the results.

```
res = conn.provisioning.create_storage_group(srp, sg, slo, workload=None, num_vols=num_vols, vol_size=vol_size, cap_unit='GB', allocate_full=True, _async=False, vol_name=vol_name)
print res
...
{u'cap_gb': 288.0, u'num_of_masking_views': 0, u'device_emulation': u'FBA', u'slo_compliance': u'NONE', u'storageGroupId': u'sg_test2', u'num_of_vols': 4, u'num_of_child_sgs': 0, u'num_of_parent_sgs': 0, u'VPSaved': u'98.1%', u'srp': u'SRP_1', u'slo': u'Diamond', u'unprotected': True, u'num_of_snapshots': 0, u'base_slo_name': u'Diamond', u'type': u'Standalone'}
```

**Comment by rawstorage** [comment]
Hi, 
we can re-examine the way the code is working,  But in +99% systems that are capable of compression it is enabled.  Pre-allocation and compression are mutually exclusive as we can not compress unwritten tracks that are allocated as we don't know how the data will compress so we need to keep the full track size in case.  I think we've hit a corner case in your environment, but we can look at addressing this in the next release.

**Comment by tzcole** [comment]
Thanks Paul,

We had compression enabled on the array, and it's working properly.
