### ISSUE TITLE
 provisioning.create_volume_from_sg_return_dev_id returns a different volume_id from name just being created

### ISSUE THREAD

**Issue by satoshi-tokyo** [dell/PyU4V#71]
# provisioning.create_volume_from_sg_return_dev_id(volume_name, storagegroup_name, vol_size, cap_unit)

Hello, I am filing something I noticed while using this module.

Same volume names can be set to different volumes, e.g., 00075:volume1108 and 00077:volume1108. Is it as expected? I an confused due to the following lab results. 

Volume_name is a required parameter, and when `volume_name=''` (`volume_name=None` worked in the same way) is specified, no volume_name is assigned. After creation, this function returns a result of `provisioning.find_volume_device_id(volume_name)` for which empty volume_name is used to look for created device_id. The very first device_id matched with this device_name is returned e.g., in my lab 00001 which is actually not the volume just created.

For that reason it looks to me that device_name needs to be unique or cannot be used an identifier of a volume. Or it could make sense if find_volume_device_id returns not only a device_id but a list of devices.

**Comment by helenwalsh** [comment]
Hi Sitaki,
Thank you for bringing this to our attention, we will look into resolving it.   You are correct, volume_name (identifier_name in REST), is either None or user defined and does not have to be unique.

**Comment by helenwalsh** [comment]
Fixed in PyU4V==3.1.6.  Thank you

**Comment by satoshi-tokyo** [comment]
Hello, and thank you for taking care of this. The device_id returned as I expected on my side as well. 
One little feedback I thought during my lab, is that when `volume_name = "" or None` specified it returns a list of device ids as below and also results in creating a volume. When a volume was created I was expecting a device_id to be returned.

```
volume name  is not unique, returning a list of device ids
['00001', ..., 'FFFEF']
```
Thinks you,

**Comment by helenwalsh** [comment]
Hi Sitaki,
You are most welcome.  I will look into the volume_name = "" or None again.  My initial thought is it will bring back a list of all volumes that were created without a volume name.  Is that what you have observed?
