### ISSUE TITLE
Error while creating the storage group.

### ISSUE THREAD

**Issue by anishxv** [dell/PyU4V#79]
Issue : Below error while creating the storage group.

Bad or unexpected response from the storage volume backend API: Error Create storagegroup resource. The status code received is 500 and the message is {'message': 'A problem occurred creating the storage group resource: java.lang.NullPointerException'}.

Command Issued : rf.provisioning.create_storage_group(srp, 'restapi_SG', 'Diamond')

Note : Earlier we were using PyU4V version: 3.0.0.1. Got the same error and updated to 3.1.5.

PyU4V  version:             3.1.5
Unisphere version     :  8.4

**Comment by helenwalsh** [comment]
Hi, we will look into this for you.  Are other rest commands working for you?  For example, can you get a storage group?

**Comment by anishxv** [comment]
rest commands like rf.provisioning.get_storage_group_list() and rf.provisioning.get_storage_group('SGNAME_SG') are working

**Comment by helenwalsh** [comment]
Thank you for bringing this to our attention, this is indeed broken on the 84 endpoint.  We will have a fix shortly.
Kind regards,
Helen

**Comment by anishxv** [comment]
Just one more thing that we upgraded vmax3 codes in our DCs 5977.1131.1131 to 5978.221.221. Observed this problem after that.

**Comment by helenwalsh** [comment]
Good to know, thank you for the additional information.

**Comment by helenwalsh** [comment]
Just on your OS upgrade to PowerMax OS(5978).  It is highly recommended to use Unisphere for PowerMax 9.0 with PowerMax OS(5978).  PyU4V 3.1.x supports 90 also.  Saying that, I was able to reproduce this issue using HyperMax (5977) on an All Flash, so it is unusual that you only saw this issue on PowerMax OS(5978).

**Comment by anishxv** [comment]
I will try to upgrade to Unishpere 9 and see how it goes.
BTW on which PyU4V , you reproduced the issue with please ?
We never faced this issue before.

**Comment by helenwalsh** [comment]
I reproduced it on PyU4V 3.1.7 on an All Flash with HyperMax OS using Unisphere for VMAX 8.4.  I was unable to reproduce the issue on Unisphere for PowerMax 9.0, so in theory, when you upgrade, all should be well as they use different REST endpoints.  I will confirm all of the above.

**Comment by anishxv** [comment]
Upgraded the Unisphere to "Unisphere for PowerMax v9.0.2.12" and we are not getting the error.

**Comment by helenwalsh** [comment]
Great news.  That was my experience also.  Regardless, I will be addressing the U4V 8.4 issue.

**Comment by helenwalsh** [comment]
I need clarify on my last posts.  The issue is only reproducible on PowerMax OS and not Hypermax OS .  Any array which has PowerMax OS must use Unisphere for PowerMax 9.0 at a minimum.
