### ISSUE TITLE
Migration between different data center.

### ISSUE THREAD

**Issue by ItsDevMonk** [dell/PyU4V#85]
Is it possible to do the migration from one data center to another data center?

**Comment by rawstorage** [comment]
Hi, 
Depends on what you need, you can use SRDF to migrate data, any flavor and do a fialover to the remote site and the data is available. 

or

There is a non-disruptive migration feature on powermax and vmax all flash arrays that utilizes SRDF to accomplish this.  We support this in PyU4V 9.1.  There are caveats to be aware of at the host side to do a non-disruptive migration as the host actions have to be controlled.  

https://www.dellemc.com/ar-sa/collaterals/unauth/technical-guides-support-information/products/storage/h17133-non-disruptive-migration-best-practices-and-operational-guide.pdf

Migration functions are under migrations module in PyU4V 9.1.
