### ISSUE TITLE
Is PyU4V v 9.1.0.3 supported for Ansible Modules for Powermax v1.1

### ISSUE THREAD

**Issue by storl0rd** [dell/PyU4V#88]
I am getting the below error while trying to run a sample playbook.

TASK [Get names of all the Storage Group] ***************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "PyU4V 9.1.3.0 is not supported by this module.Minimum supported version is : 3.1.5 and less than 4.0.0 "}

**Comment by rawstorage** [comment]
the error is pretty clear you have the wrong version of PyU4V for the modules, you need to do the following.. Next release of Ansible modules will support PyU4V 9.1 so you won't run into this.

python -m pip uninstall PyU4V
then
python -m pip install PyU4V==3.1.7
This is documented in the install guide on the github..
https://github.com/dell/ansible-powermax/

**Comment by storl0rd** [comment]
Thank you very much, I will remove the current version and install 3.1.7
