### ISSUE TITLE
PyU4V latest in Pypi

### ISSUE THREAD

**Issue by mallilinux1978** [dell/PyU4V#9]
Hi, whatever i find in PyPI (https://pypi.python.org/pypi/PyU4V/1.0.2) is bit outdated I believe. Any idea when it will have latest code?

thanks,
Mallik.

**Comment by ciarams87** [comment]
Hi Mallik,

I will be creating a new pip release in the next few days, The next release will also include Unisphere version 8.4 functionality.

Many thanks,
Ciara
