### ISSUE TITLE
Volume Performance Metrics

### ISSUE THREAD

**Issue by abmaymic** [dell/PyU4V#91]
I'm searching for (Thin) Volume Performance Metrics. I didn't find the right function on the API for that. Is there any?

Best regards,

Michael

**Comment by MichaelMcAleer** [comment]
Hi Michael,

Performance metrics for volumes are not available in Unisphere and as such we cannot report on them through PyU4V.  It is assumed that using a combination of other reporting categories that a clear picture of environment performance can be achieved.

**Comment by abmaymic** [comment]
Hi Michael,

Thanks a lot for your answer. Just to get it right: 'not available in Unisphere' means on API-level of Unisphere? Because on the Powermax-UI I can see these metrics. 

Metrics per Volume would be of interest for us when it comes to troubleshooting and optimization of some of our workloads. Is there an alternative way/API to get these metrics on Powermax?

Best regards,

Michael

**Comment by MichaelMcAleer** [comment]
Hi Michael,

Yes that is correct, volume level metrics are not available through the Unisphere REST API so they won't be in PyU4V. Unfortunately there is no other way to view thin volume level metrics than via the Unisphere UI.

We do have calls for workload planner that will give you headroom details if that is of any use in your workload optimization. 

Hope this helps,
Michael
