### ISSUE TITLE
conn.provisioning.create_storage_group Fails to Create Volumes

### ISSUE THREAD

**Issue by prolly-brent** [dell/PyU4V#93]
Greetings:

I'm using PyU4V 9.1.3.0 with a new PowerMax2000.  I am trying to create a new storage group with a couple of volumes to go with it.  The "conn.provisioning.create_storage_group" function advertises the ability to do this.  However, when I execute the function, it only creates the storage group (no volumes).  To workaround, I have to first create an empty storage group and then create/add the volumes in a separate step. 

srp = 'SRP_1'
sg_id = 'brent-local-sg'
slo = ''
num_vols = 2
vol_size = '58006'
cap_unit = 'CYL'

response = conn.provisioning.create_storage_group( srp,
                                                   sg_id,
                                                   slo,
                                                   workload=None,
                                                   do_disable_compression=False,
                                                   num_vols=num_vols,
                                                   vol_size=vol_size,
                                                   cap_unit=cap_unit,
                                                   allocate_full=False,
                                                   _async=False,
                                                   vol_name=None
                                                 )

Here's the response dictionary after execution.  I am expecting two volumes to be created.
{
    "cap_gb": 0.0,
    "compression": false,
    "device_emulation": "N/A",
    "num_of_child_sgs": 0,
    "num_of_masking_views": 0,
    "num_of_parent_sgs": 0,
    "num_of_snapshots": 0,
    "num_of_vols": 0,
    "slo": "NONE",
    "slo_compliance": "NONE",
    "storageGroupId": "brent-local-sg",
    "type": "Standalone",
    "unprotected": true
}

Thanks,
Brent

**Comment by MichaelMcAleer** [comment]
Hi Brent,

Thanks for flagging this, ill run a few tests locally and see what goes on in my own environment. 

In the interim can you send over your environment info and logs, some info available on what we need in our docs: https://pyu4v.readthedocs.io/en/latest/support.html

Thanks!
Michel

**Comment by MichaelMcAleer** [comment]
Actually no need to send over any more info Brent, I've found what is wrong here. When `slo` is set to `None` or empty string we have an if condition in `create_storage_group()` that doesn't get met and as a result we don't include the relevant info for the number of volumes required and what size, just that we want a SG so that would explain your empty SG response. I have verified this in my own environment, building a fix today so you will see a new minor version soon.

Thanks again for flagging!

**Comment by prolly-brent** [comment]
Thanks Michael.

Regards,
Brent

**Comment by MichaelMcAleer** [comment]
This issue has been resolved in pull request #94. CI needs to be run on the changes before we can merge it to master, an issue in our lab is going to prevent that until the middle of next week as Monday is a bank holiday here in Ireland.

If you would like to test the fix feel free but be aware it is still subject to change pending the results of CI tests, you can find the fixed create_storage_group() function [here](https://github.com/dell/PyU4V/blob/9af280dee25b3c5e9b97adb8a0340d712c37f4d0/PyU4V/provisioning.py#L1540) or you can just pull the branch associated with the pull request.
