### ISSUE TITLE
Can we a create a new storage group or a volume from a storage group snapshot.

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#95]
Hi
I am currently working on the DELL EMC VMax Array and i am exploring how can we create a storage group from and existing snapshot of storage group or can we create a specific volume from a storage group snapshot.

The modify_storage_group_snapshot does provide modification, but to only link/ unlink, name, generation number updates.

**Comment by helenwalsh** [comment]
Hi Gupta,
Referring you to a test that I think should help.  It creates a target storage group from source storage group using a snapvx.
https://github.com/dell/PyU4V/blob/master/PyU4V/tests/ci_tests/test_pyu4v_ci_replication.py#L123

**Comment by mukeshguptakc** [comment]
Hi Helenwalsh,

Thanks, for the reference i'll try that and see if that resolves the purpose.
