### ISSUE TITLE
Can we attach/map a storage group snapshot to any host

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#96]
Hi
Currently, we are working with VMax and PowerMax Array too qualify for snapshot orchestration and we need to attach a snapshot if possible or a volume carved from the snapshot to a host/server.

The modify_storage_group_snapshot does provide modification, but to only link/ unlink, name, generation number updates.
But attaching a storage group snapshot methods could not be found.

**Comment by helenwalsh** [comment]
Hi Gupta,
You will first need to create a storage group from the snapshot as you cannot attach a snapshot on the PowerMax/VMAX (see last post)
The storage group will need to belong to a masking view, that also contains an initiator group (containing the host initiator(s)) and a port group (containing ports to access the array).  
There are good examples here.
https://github.com/dell/PyU4V/blob/master/PyU4V/tests/ci_tests/test_pyu4v_ci_provisioning.py

Thank you
Helen

**Comment by mukeshguptakc** [comment]
Hi Helenwalsh,

Thanks, for the test references. I'll try the way you suggested.

Thankyou.
