### ISSUE TITLE
Restore a volume in a storage group from storage group snapshot.

### ISSUE THREAD

**Issue by mukeshguptakc** [dell/PyU4V#97]
Currently, we are working with VMax and PowerMax Array too qualify for snapshot orchestration.

For a restore scenario **restore_snapshot**, restores the storage group to its snapshot.
Can we restore a single volume from a storage group snapshot.

**Comment by mukeshguptakc** [comment]
modify_snapshot would restore the storage group to previous state and the required volume can be fetched.

**Comment by rawstorage** [comment]
the API works at the storage group level to restore a single volume you would need to place that volume in a storage group on it's own to restore just that volume. 

A volume can be a member of multiple storage groups.  
The things to remember here are 
- That the new SG shouldn't be associated with SRP or have Service Level.  
- Once the device is restored you need to terminate the restore session
- you probably want to delete the temporary storage group when done.

**Comment by mukeshguptakc** [comment]
Thanks, Paul.
I'll try out the restore as suggested.
